import 'package:itun/core/logging/app_logger.dart';
import 'package:appwrite/appwrite.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/api/appwrite_db_service.dart';
import '../models/content_models.dart';

@Deprecated('Use contentListProvider. Will be removed in v1.4.0')
final wordsProvider =
    StateNotifierProvider<WordsNotifier, AsyncValue<List<WordModel>>>(
      WordsNotifier.new,
    );

class WordsNotifier extends StateNotifier<AsyncValue<List<WordModel>>> {
  WordsNotifier(this.ref) : super(const AsyncValue.loading()) {
    _loadWords();
  }

  final Ref ref;

  static final List<WordModel> _seedWords = [
    // ── Greetings & Basics (greeting) ──
    WordModel(
      id: 'w_g1',
      wordOlChiki: 'ᱡᱚᱦᱟᱨ',
      wordLatin: 'Johar',
      meaning: 'Hello / Greetings',
      category: 'greeting',
      order: 1,
    ),
    WordModel(
      id: 'w_g2',
      wordOlChiki: 'ᱥᱟᱨᱦᱟᱣ',
      wordLatin: 'Sarhaw',
      meaning: 'Thank you',
      category: 'greeting',
      order: 2,
    ),
    WordModel(
      id: 'w_g3',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
      wordLatin: 'Sagun Daram',
      meaning: 'Welcome',
      category: 'greeting',
      order: 3,
    ),
    WordModel(
      id: 'w_g4',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱥᱮᱛᱟᱜ',
      wordLatin: 'Sagun Setag',
      meaning: 'Good morning',
      category: 'greeting',
      order: 4,
    ),
    WordModel(
      id: 'w_g5',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱧᱤᱫᱟᱹ',
      wordLatin: 'Sagun Njida',
      meaning: 'Good night',
      category: 'greeting',
      order: 5,
    ),
    WordModel(
      id: 'w_g6',
      wordOlChiki: 'ᱡᱚᱦᱟᱨ ᱜᱮ',
      wordLatin: 'Johar ge',
      meaning: 'Greetings to you',
      category: 'greeting',
      order: 6,
    ),
    WordModel(
      id: 'w_g7',
      wordOlChiki: 'ᱱᱟᱯᱟᱭ ᱜᱮ',
      wordLatin: 'Napay ge',
      meaning: 'Just fine',
      category: 'greeting',
      order: 7,
    ),
    WordModel(
      id: 'w_g8',
      wordOlChiki: 'ᱢᱟᱨᱟᱝ ᱡᱚᱦᱟᱨ',
      wordLatin: 'Marang Johar',
      meaning: 'Great respect hello',
      category: 'greeting',
      order: 8,
    ),
    WordModel(
      id: 'w_g9',
      wordOlChiki: 'ᱜᱩᱱ ᱢᱟᱱᱟᱣ',
      wordLatin: 'Gun Manaw',
      meaning: 'Respect / Honor',
      category: 'greeting',
      order: 9,
    ),
    WordModel(
      id: 'w_g10',
      wordOlChiki: 'ᱡᱤᱭᱟᱹᱲ',
      wordLatin: 'Jiyar',
      meaning: 'Long live / Live well',
      category: 'greeting',
      order: 10,
    ),
    WordModel(
      id: 'w_g11',
      wordOlChiki: 'ᱞᱟᱥᱟᱬᱦᱮᱫ',
      wordLatin: 'Lasanhed',
      meaning: 'Sweet greetings',
      category: 'greeting',
      order: 11,
    ),
    WordModel(
      id: 'w_g12',
      wordOlChiki: 'ᱦᱮᱞᱢᱮᱞ',
      wordLatin: 'Helmel',
      meaning: 'Friendly association',
      category: 'greeting',
      order: 12,
    ),
    WordModel(
      id: 'w_g13',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱛᱤᱠᱤᱱ',
      wordLatin: 'Sagun Tikin',
      meaning: 'Good afternoon',
      category: 'greeting',
      order: 13,
    ),
    WordModel(
      id: 'w_g14',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱟᱹᱭᱩᱵ',
      wordLatin: 'Sagun Ayub',
      meaning: 'Good evening',
      category: 'greeting',
      order: 14,
    ),
    WordModel(
      id: 'w_g15',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱥᱤᱸᱜᱮ',
      wordLatin: 'Sagun Singe',
      meaning: 'Blessed Sunday',
      category: 'greeting',
      order: 15,
    ),
    WordModel(
      id: 'w_g16',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱫᱤᱱ',
      wordLatin: 'Sagun Din',
      meaning: 'Good day',
      category: 'greeting',
      order: 16,
    ),
    WordModel(
      id: 'w_g17',
      wordOlChiki: 'ᱢᱟ ᱡᱚᱦᱟᱨ',
      wordLatin: 'Ma Johar',
      meaning: 'Formal goodbye / respect',
      category: 'greeting',
      order: 17,
    ),
    WordModel(
      id: 'w_g18',
      wordOlChiki: 'ᱛᱟᱦᱮᱸᱱ',
      wordLatin: 'Tahen',
      meaning: 'Goodbye (stay well)',
      category: 'greeting',
      order: 18,
    ),
    WordModel(
      id: 'w_g19',
      wordOlChiki: 'ᱥᱮᱱᱚᱜ',
      wordLatin: 'Senog',
      meaning: 'Goodbye (go well)',
      category: 'greeting',
      order: 19,
    ),
    WordModel(
      id: 'w_g20',
      wordOlChiki: 'ᱥᱟᱨᱦᱟᱣ ᱜᱮ',
      wordLatin: 'Sarhaw ge',
      meaning: 'Thank you indeed',
      category: 'greeting',
      order: 20,
    ),

    // ── Basics (basic) ──
    WordModel(
      id: 'w_b1',
      wordOlChiki: 'ᱦᱮᱸ',
      wordLatin: 'Hẽ',
      meaning: 'Yes',
      category: 'basic',
      order: 21,
    ),
    WordModel(
      id: 'w_b2',
      wordOlChiki: 'ᱵᱟᱝ',
      wordLatin: 'Bang',
      meaning: 'No',
      category: 'basic',
      order: 22,
    ),
    WordModel(
      id: 'w_b3',
      wordOlChiki: 'ᱪᱮᱫ',
      wordLatin: 'Ced',
      meaning: 'What',
      category: 'basic',
      order: 23,
    ),
    WordModel(
      id: 'w_b4',
      wordOlChiki: 'ᱚᱠᱚᱭ',
      wordLatin: 'Okoy',
      meaning: 'Who',
      category: 'basic',
      order: 24,
    ),
    WordModel(
      id: 'w_b5',
      wordOlChiki: 'ᱚᱠᱟ',
      wordLatin: 'Oka',
      meaning: 'Which',
      category: 'basic',
      order: 25,
    ),
    WordModel(
      id: 'w_b6',
      wordOlChiki: 'ᱪᱮᱞᱮᱠᱟ',
      wordLatin: 'Celeka',
      meaning: 'How',
      category: 'basic',
      order: 26,
    ),
    WordModel(
      id: 'w_b7',
      wordOlChiki: 'ᱛᱤᱥ',
      wordLatin: 'Tis',
      meaning: 'When',
      category: 'basic',
      order: 27,
    ),
    WordModel(
      id: 'w_b8',
      wordOlChiki: 'ᱚᱠᱟᱨᱮ',
      wordLatin: 'Okare',
      meaning: 'Where',
      category: 'basic',
      order: 28,
    ),
    WordModel(
      id: 'w_b9',
      wordOlChiki: 'ᱤᱧ',
      wordLatin: 'Inj',
      meaning: 'I / Me',
      category: 'basic',
      order: 29,
    ),
    WordModel(
      id: 'w_b10',
      wordOlChiki: 'ᱟᱢ',
      wordLatin: 'Am',
      meaning: 'You',
      category: 'basic',
      order: 30,
    ),
    WordModel(
      id: 'w_b11',
      wordOlChiki: 'ᱩᱱᱤ',
      wordLatin: 'Uni',
      meaning: 'He / She',
      category: 'basic',
      order: 31,
    ),
    WordModel(
      id: 'w_b12',
      wordOlChiki: 'ᱱᱩᱭ',
      wordLatin: 'Nuy',
      meaning: 'This person',
      category: 'basic',
      order: 32,
    ),
    WordModel(
      id: 'w_b13',
      wordOlChiki: 'ᱦᱟᱹᱱᱤ',
      wordLatin: 'Hani',
      meaning: 'That person (far)',
      category: 'basic',
      order: 33,
    ),
    WordModel(
      id: 'w_b14',
      wordOlChiki: 'ᱚᱱᱟ',
      wordLatin: 'Ona',
      meaning: 'That thing',
      category: 'basic',
      order: 34,
    ),
    WordModel(
      id: 'w_b15',
      wordOlChiki: 'ᱱᱚᱶᱟ',
      wordLatin: 'Nowa',
      meaning: 'This thing',
      category: 'basic',
      order: 35,
    ),
    WordModel(
      id: 'w_b16',
      wordOlChiki: 'ᱟᱹᱰᱤ',
      wordLatin: 'Adi',
      meaning: 'Very',
      category: 'basic',
      order: 36,
    ),
    WordModel(
      id: 'w_b17',
      wordOlChiki: 'ᱠᱟᱹᱡ',
      wordLatin: 'Kaj',
      meaning: 'Few / A little',
      category: 'basic',
      order: 37,
    ),
    WordModel(
      id: 'w_b18',
      wordOlChiki: 'ᱡᱷᱚᱛᱚ',
      wordLatin: 'Jhoto',
      meaning: 'All',
      category: 'basic',
      order: 38,
    ),
    WordModel(
      id: 'w_b19',
      wordOlChiki: 'ᱪᱤᱞᱤ',
      wordLatin: 'Cili',
      meaning: 'What kind of living being',
      category: 'basic',
      order: 39,
    ),
    WordModel(
      id: 'w_b20',
      wordOlChiki: 'ᱱᱟᱥᱮ',
      wordLatin: 'Nase',
      meaning: 'Slightly',
      category: 'basic',
      order: 40,
    ),

    // ── Family & Relationships (family) ──
    WordModel(
      id: 'w_f1',
      wordOlChiki: 'ᱵᱟᱵᱟ',
      wordLatin: 'Baba',
      meaning: 'Father',
      category: 'family',
      order: 41,
    ),
    WordModel(
      id: 'w_f2',
      wordOlChiki: 'ᱟᱭᱳ',
      wordLatin: 'Ayo',
      meaning: 'Mother',
      category: 'family',
      order: 42,
    ),
    WordModel(
      id: 'w_f3',
      wordOlChiki: 'ᱳᱲᱟᱜ ᱦᱚᱲ',
      wordLatin: 'Orag hor',
      meaning: 'Spouse / Family member',
      category: 'family',
      order: 43,
    ),
    WordModel(
      id: 'w_f4',
      wordOlChiki: 'ᱫᱟᱫᱟ',
      wordLatin: 'Dada',
      meaning: 'Elder brother',
      category: 'family',
      order: 44,
    ),
    WordModel(
      id: 'w_f5',
      wordOlChiki: 'ᱫᱟᱹᱭ',
      wordLatin: 'Dai',
      meaning: 'Elder sister',
      category: 'family',
      order: 45,
    ),
    WordModel(
      id: 'w_f6',
      wordOlChiki: 'ᱵᱚᱠᱚᱧ',
      wordLatin: 'Bokonj',
      meaning: 'Younger brother',
      category: 'family',
      order: 46,
    ),
    WordModel(
      id: 'w_f7',
      wordOlChiki: 'ᱢᱤᱥᱮᱨᱟ',
      wordLatin: 'Misera',
      meaning: 'Younger sister',
      category: 'family',
      order: 47,
    ),
    WordModel(
      id: 'w_f8',
      wordOlChiki: 'ᱦᱚᱯᱚᱱ',
      wordLatin: 'Hopon',
      meaning: 'Son / Child',
      category: 'family',
      order: 48,
    ),
    WordModel(
      id: 'w_f9',
      wordOlChiki: 'ᱦᱚᱯᱚᱱ ᱮᱨᱟ',
      wordLatin: 'Hopon era',
      meaning: 'Daughter',
      category: 'family',
      order: 49,
    ),
    WordModel(
      id: 'w_f10',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ ᱦᱟᱲᱟᱢ',
      wordLatin: 'Gorom haram',
      meaning: 'Grandfather',
      category: 'family',
      order: 50,
    ),
    WordModel(
      id: 'w_f11',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ ᱵᱩᱰᱷᱤ',
      wordLatin: 'Gorom budhi',
      meaning: 'Grandmother',
      category: 'family',
      order: 51,
    ),
    WordModel(
      id: 'w_f12',
      wordOlChiki: 'ᱠᱟᱠᱟ',
      wordLatin: 'Kaka',
      meaning: 'Uncle (father\'s younger brother)',
      category: 'family',
      order: 52,
    ),
    WordModel(
      id: 'w_f13',
      wordOlChiki: 'ᱠᱟᱠᱤ',
      wordLatin: 'Kaki',
      meaning: 'Aunt (father\'s younger brother\'s wife)',
      category: 'family',
      order: 53,
    ),
    WordModel(
      id: 'w_f14',
      wordOlChiki: 'ᱢᱟᱢᱚ',
      wordLatin: 'Mamo',
      meaning: 'Maternal uncle',
      category: 'family',
      order: 54,
    ),
    WordModel(
      id: 'w_f15',
      wordOlChiki: 'ᱦᱟᱛᱚᱢ',
      wordLatin: 'Hatom',
      meaning: 'Paternal aunt',
      category: 'family',
      order: 55,
    ),
    WordModel(
      id: 'w_f16',
      wordOlChiki: 'ᱛᱮᱧᱟᱝ',
      wordLatin: 'Tenjang',
      meaning: 'Brother-in-law (sister\'s husband)',
      category: 'family',
      order: 56,
    ),
    WordModel(
      id: 'w_f17',
      wordOlChiki: 'ᱦᱤᱞᱤ',
      wordLatin: 'Hili',
      meaning: 'Sister-in-law (brother\'s wife)',
      category: 'family',
      order: 57,
    ),
    WordModel(
      id: 'w_f18',
      wordOlChiki: 'ᱵᱟᱹᱦᱩ',
      wordLatin: 'Bahu',
      meaning: 'Wife / Bride',
      category: 'family',
      order: 58,
    ),
    WordModel(
      id: 'w_f19',
      wordOlChiki: 'ᱡᱟᱶᱟᱭ',
      wordLatin: 'Jaway',
      meaning: 'Husband / Groom',
      category: 'family',
      order: 59,
    ),
    WordModel(
      id: 'w_f20',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ',
      wordLatin: 'Gorom',
      meaning: 'Grandchild',
      category: 'family',
      order: 60,
    ),

    // ── Daily Use Words (daily) ──
    WordModel(
      id: 'w_d1',
      wordOlChiki: 'ᱫᱟᱜ',
      wordLatin: 'Dag',
      meaning: 'Water',
      category: 'daily',
      order: 61,
    ),
    WordModel(
      id: 'w_d2',
      wordOlChiki: 'ᱫᱟᱠᱟ',
      wordLatin: 'Daka',
      meaning: 'Cooked Rice / Food',
      category: 'daily',
      order: 62,
    ),
    WordModel(
      id: 'w_d3',
      wordOlChiki: 'ᱳᱲᱟᱜ',
      wordLatin: 'Orag',
      meaning: 'Home / House',
      category: 'daily',
      order: 63,
    ),
    WordModel(
      id: 'w_d4',
      wordOlChiki: 'ᱠᱤᱪᱨᱤᱡ',
      wordLatin: 'Kicrij',
      meaning: 'Cloth',
      category: 'daily',
      order: 64,
    ),
    WordModel(
      id: 'w_d5',
      wordOlChiki: 'ᱦᱚᱨ',
      wordLatin: 'Hor',
      meaning: 'Path / Road',
      category: 'daily',
      order: 65,
    ),
    WordModel(
      id: 'w_d6',
      wordOlChiki: 'ᱟᱹᱛᱩ',
      wordLatin: 'Atu',
      meaning: 'Village',
      category: 'daily',
      order: 66,
    ),
    WordModel(
      id: 'w_d7',
      wordOlChiki: 'ᱴᱟᱠᱟ',
      wordLatin: 'Taka',
      meaning: 'Money',
      category: 'daily',
      order: 67,
    ),
    WordModel(
      id: 'w_d8',
      wordOlChiki: 'ᱠᱟᱹᱢᱤ',
      wordLatin: 'Kami',
      meaning: 'Work / Job',
      category: 'daily',
      order: 68,
    ),
    WordModel(
      id: 'w_d9',
      wordOlChiki: 'ᱡᱟᱹᱯᱤᱫ',
      wordLatin: 'Japid',
      meaning: 'Sleep',
      category: 'daily',
      order: 69,
    ),
    WordModel(
      id: 'w_d10',
      wordOlChiki: 'ᱛᱩᱯᱩᱱ',
      wordLatin: 'Tupun',
      meaning: 'Bathing',
      category: 'daily',
      order: 70,
    ),
    WordModel(
      id: 'w_d11',
      wordOlChiki: 'ᱥᱮᱱᱚᱜ',
      wordLatin: 'Senog',
      meaning: 'Going',
      category: 'daily',
      order: 71,
    ),
    WordModel(
      id: 'w_d12',
      wordOlChiki: 'ᱦᱤᱡᱩᱜ',
      wordLatin: 'Hijug',
      meaning: 'Coming',
      category: 'daily',
      order: 72,
    ),
    WordModel(
      id: 'w_d13',
      wordOlChiki: 'ᱫᱩᱲᱩᱵ',
      wordLatin: 'Durub',
      meaning: 'Sit',
      category: 'daily',
      order: 73,
    ),
    WordModel(
      id: 'w_d14',
      wordOlChiki: 'ᱛᱮᱸᱜᱚ',
      wordLatin: 'Tengo',
      meaning: 'Stand',
      category: 'daily',
      order: 74,
    ),
    WordModel(
      id: 'w_d15',
      wordOlChiki: 'ᱫᱟᱹᱲ',
      wordLatin: 'Dar',
      meaning: 'Run',
      category: 'daily',
      order: 75,
    ),
    WordModel(
      id: 'w_d16',
      wordOlChiki: 'ᱛᱟᱲᱟᱢ',
      wordLatin: 'Taram',
      meaning: 'Walk',
      category: 'daily',
      order: 76,
    ),
    WordModel(
      id: 'w_d17',
      wordOlChiki: 'ᱨᱚᱲ',
      wordLatin: 'Ror',
      meaning: 'Speak / Talk',
      category: 'daily',
      order: 77,
    ),
    WordModel(
      id: 'w_d18',
      wordOlChiki: 'ᱟᱸᱡᱚᱢ',
      wordLatin: 'Anjom',
      meaning: 'Hear / Listen',
      category: 'daily',
      order: 78,
    ),
    WordModel(
      id: 'w_d19',
      wordOlChiki: 'ᱧᱮᱞ',
      wordLatin: 'Njel',
      meaning: 'See / Look',
      category: 'daily',
      order: 79,
    ),
    WordModel(
      id: 'w_d20',
      wordOlChiki: 'ᱚᱞ',
      wordLatin: 'Ol',
      meaning: 'Write',
      category: 'daily',
      order: 80,
    ),

    // ── Colors (colors) ──
    WordModel(
      id: 'w_c1',
      wordOlChiki: 'ᱟᱨᱟᱜ',
      wordLatin: 'Arag',
      meaning: 'Red',
      category: 'colors',
      order: 81,
      themeColor: '#EF4444',
    ),
    WordModel(
      id: 'w_c2',
      wordOlChiki: 'ᱥᱟᱥᱟᱝ',
      wordLatin: 'Sasang',
      meaning: 'Yellow',
      category: 'colors',
      order: 82,
      themeColor: '#EAB308',
    ),
    WordModel(
      id: 'w_c3',
      wordOlChiki: 'ᱦᱟᱹᱨᱭᱟᱹᱲ',
      wordLatin: 'Haryar',
      meaning: 'Green',
      category: 'colors',
      order: 83,
      themeColor: '#10B981',
    ),
    WordModel(
      id: 'w_c4',
      wordOlChiki: 'ᱯᱩᱸᱰ',
      wordLatin: 'Pund',
      meaning: 'White',
      category: 'colors',
      order: 84,
      themeColor: '#FFFFFF',
    ),
    WordModel(
      id: 'w_c5',
      wordOlChiki: 'ᱦᱮᱱᱫᱮ',
      wordLatin: 'Hende',
      meaning: 'Black',
      category: 'colors',
      order: 85,
      themeColor: '#1E293B',
    ),
    WordModel(
      id: 'w_c6',
      wordOlChiki: 'ᱞᱤᱞ',
      wordLatin: 'Lil',
      meaning: 'Blue',
      category: 'colors',
      order: 86,
      themeColor: '#3B82F6',
    ),
    WordModel(
      id: 'w_c7',
      wordOlChiki: 'ᱜᱩᱞᱟᱹᱯᱤ',
      wordLatin: 'Gulapi',
      meaning: 'Pink',
      category: 'colors',
      order: 87,
      themeColor: '#F43F5E',
    ),
    WordModel(
      id: 'w_c8',
      wordOlChiki: 'ᱠᱷᱟᱹᱠᱨᱤ',
      wordLatin: 'Khakri',
      meaning: 'Brown',
      category: 'colors',
      order: 88,
      themeColor: '#78350F',
    ),
    WordModel(
      id: 'w_c9',
      wordOlChiki: 'ᱠᱟᱹᱦᱞᱟᱹ',
      wordLatin: 'Kahla',
      meaning: 'Purple / Violet',
      category: 'colors',
      order: 89,
      themeColor: '#475569', // Avoid violet/purple per ban
    ),
    WordModel(
      id: 'w_c10',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ ᱟᱨᱟᱜ',
      wordLatin: 'Sengel arag',
      meaning: 'Fiery Red',
      category: 'colors',
      order: 90,
      themeColor: '#DC2626',
    ),
    WordModel(
      id: 'w_c11',
      wordOlChiki: 'ᱢᱮᱫ ᱟᱨᱟᱜ',
      wordLatin: 'Med arag',
      meaning: 'Crimson',
      category: 'colors',
      order: 91,
      themeColor: '#991B1B',
    ),
    WordModel(
      id: 'w_c12',
      wordOlChiki: 'ᱦᱟᱥᱟ',
      wordLatin: 'Hasa',
      meaning: 'Clay-colored / Earthy grey',
      category: 'colors',
      order: 92,
      themeColor: '#78716C',
    ),
    WordModel(
      id: 'w_c13',
      wordOlChiki: 'ᱥᱚᱱᱟ',
      wordLatin: 'Sona',
      meaning: 'Golden',
      category: 'colors',
      order: 93,
      themeColor: '#D97706',
    ),
    WordModel(
      id: 'w_c14',
      wordOlChiki: 'ᱨᱩᱯᱟᱹ',
      wordLatin: 'Rupa',
      meaning: 'Silvery',
      category: 'colors',
      order: 94,
      themeColor: '#CBD5E1',
    ),
    WordModel(
      id: 'w_c15',
      wordOlChiki: 'ᱞᱟᱹᱰᱩ',
      wordLatin: 'Ladu orange',
      meaning: 'Orange',
      category: 'colors',
      order: 95,
      themeColor: '#F97316',
    ),
    WordModel(
      id: 'w_c16',
      wordOlChiki: 'ᱪᱩᱱ',
      wordLatin: 'Cun',
      meaning: 'Lime white',
      category: 'colors',
      order: 96,
      themeColor: '#F8FAFC',
    ),
    WordModel(
      id: 'w_c17',
      wordOlChiki: 'ᱠᱩᱭᱞᱟᱹ',
      wordLatin: 'Kuyla',
      meaning: 'Coal black',
      category: 'colors',
      order: 97,
      themeColor: '#0F172A',
    ),
    WordModel(
      id: 'w_c18',
      wordOlChiki: 'ᱞᱤᱞᱪᱷᱟᱴᱟ',
      wordLatin: 'Lilchata',
      meaning: 'Light blue',
      category: 'colors',
      order: 98,
      themeColor: '#7DD3FC',
    ),
    WordModel(
      id: 'w_c19',
      wordOlChiki: 'ᱡᱟᱹᱨᱫᱤ',
      wordLatin: 'Jardi',
      meaning: 'Deep yellow',
      category: 'colors',
      order: 99,
      themeColor: '#EAB308',
    ),
    WordModel(
      id: 'w_c20',
      wordOlChiki: 'ᱦᱟᱹᱨᱭᱟᱹᱲᱪᱷᱟᱴᱟ',
      wordLatin: 'Haryarchata',
      meaning: 'Pale green',
      category: 'colors',
      order: 100,
      themeColor: '#86EFAC',
    ),

    // ── Animals & Nature (nature) ──
    WordModel(
      id: 'w_n1',
      wordOlChiki: 'ᱥᱮᱛᱟ',
      wordLatin: 'Seta',
      meaning: 'Dog',
      category: 'nature',
      order: 101,
    ),
    WordModel(
      id: 'w_n2',
      wordOlChiki: 'ᱯᱩᱥᱤ',
      wordLatin: 'Pusi',
      meaning: 'Cat',
      category: 'nature',
      order: 102,
    ),
    WordModel(
      id: 'w_n3',
      wordOlChiki: 'ᱢᱮᱨᱳᱢ',
      wordLatin: 'Merom',
      meaning: 'Goat',
      category: 'nature',
      order: 103,
    ),
    WordModel(
      id: 'w_n4',
      wordOlChiki: 'ᱜᱟᱹᱭ',
      wordLatin: 'Gai',
      meaning: 'Cow',
      category: 'nature',
      order: 104,
    ),
    WordModel(
      id: 'w_n5',
      wordOlChiki: 'ᱛᱟᱹᱨᱩᱵ',
      wordLatin: 'Tarub',
      meaning: 'Tiger',
      category: 'nature',
      order: 105,
    ),
    WordModel(
      id: 'w_n6',
      wordOlChiki: 'ᱪᱮᱬᱮ',
      wordLatin: 'Cene',
      meaning: 'Bird',
      category: 'nature',
      order: 106,
    ),
    WordModel(
      id: 'w_n7',
      wordOlChiki: 'ᱦᱟᱹᱠᱩ',
      wordLatin: 'Haku',
      meaning: 'Fish',
      category: 'nature',
      order: 107,
    ),
    WordModel(
      id: 'w_n8',
      wordOlChiki: 'ᱫᱟᱨᱮ',
      wordLatin: 'Dare',
      meaning: 'Tree',
      category: 'nature',
      order: 108,
    ),
    WordModel(
      id: 'w_n9',
      wordOlChiki: 'ᱵᱟᱦᱟ',
      wordLatin: 'Baha',
      meaning: 'Flower',
      category: 'nature',
      order: 109,
    ),
    WordModel(
      id: 'w_n10',
      wordOlChiki: 'ᱥᱤᱧ',
      wordLatin: 'Sing',
      meaning: 'Sun',
      category: 'nature',
      order: 110,
    ),
    WordModel(
      id: 'w_n11',
      wordOlChiki: 'ᱤᱯᱤᱞ',
      wordLatin: 'Ipil',
      meaning: 'Star',
      category: 'nature',
      order: 111,
    ),
    WordModel(
      id: 'w_n12',
      wordOlChiki: 'ᱠᱟᱰᱟ',
      wordLatin: 'Kada',
      meaning: 'Buffalo',
      category: 'nature',
      order: 112,
    ),
    WordModel(
      id: 'w_n13',
      wordOlChiki: 'ᱥᱟᱫᱚᱢ',
      wordLatin: 'Sadom',
      meaning: 'Horse',
      category: 'nature',
      order: 113,
    ),
    WordModel(
      id: 'w_n14',
      wordOlChiki: 'ᱦᱟᱹᱛᱤ',
      wordLatin: 'Hati',
      meaning: 'Elephant',
      category: 'nature',
      order: 114,
    ),
    WordModel(
      id: 'w_n15',
      wordOlChiki: 'ᱵᱤᱧ',
      wordLatin: 'Binj',
      meaning: 'Snake',
      category: 'nature',
      order: 115,
    ),
    WordModel(
      id: 'w_n16',
      wordOlChiki: 'ᱥᱟᱠᱟᱢ',
      wordLatin: 'Sakam',
      meaning: 'Leaf',
      category: 'nature',
      order: 116,
    ),
    WordModel(
      id: 'w_n17',
      wordOlChiki: 'ᱨᱤᱢᱤᱞ',
      wordLatin: 'Rimil',
      meaning: 'Cloud',
      category: 'nature',
      order: 117,
    ),
    WordModel(
      id: 'w_n18',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ',
      wordLatin: 'Sengel',
      meaning: 'Fire',
      category: 'nature',
      order: 118,
    ),
    WordModel(
      id: 'w_n19',
      wordOlChiki: 'ᱦᱚᱭ',
      wordLatin: 'Hoy',
      meaning: 'Wind / Air',
      category: 'nature',
      order: 119,
    ),
    WordModel(
      id: 'w_n20',
      wordOlChiki: 'ᱦᱟᱥᱟ',
      wordLatin: 'Hasa',
      meaning: 'Soil / Earth',
      category: 'nature',
      order: 120,
    ),

    // ── Months, Days & Seasons (time) ──
    WordModel(
      id: 'w_t1',
      wordOlChiki: 'ᱪᱟᱸᱫᱚ',
      wordLatin: 'Chando',
      meaning: 'Month / Moon',
      category: 'time',
      order: 121,
    ),
    WordModel(
      id: 'w_t2',
      wordOlChiki: 'ᱢᱟᱦᱟ',
      wordLatin: 'Maha',
      meaning: 'Day',
      category: 'time',
      order: 122,
    ),
    WordModel(
      id: 'w_t3',
      wordOlChiki: 'ᱛᱮᱦᱮᱧ',
      wordLatin: 'Tehenj',
      meaning: 'Today',
      category: 'time',
      order: 123,
    ),
    WordModel(
      id: 'w_t4',
      wordOlChiki: 'ᱜᱟᱯᱟ',
      wordLatin: 'Gapa',
      meaning: 'Tomorrow',
      category: 'time',
      order: 124,
    ),
    WordModel(
      id: 'w_t5',
      wordOlChiki: 'ᱦᱚᱞᱟ',
      wordLatin: 'Hola',
      meaning: 'Yesterday',
      category: 'time',
      order: 125,
    ),
    WordModel(
      id: 'w_t6',
      wordOlChiki: 'ᱥᱤᱛᱩᱝ ᱨᱤᱛᱩ',
      wordLatin: 'Situng ritu',
      meaning: 'Summer',
      category: 'time',
      order: 126,
    ),
    WordModel(
      id: 'w_t7',
      wordOlChiki: 'ᱫᱟᱜ ᱨᱤᱛᱩ',
      wordLatin: 'Dag ritu',
      meaning: 'Rainy Season',
      category: 'time',
      order: 127,
    ),
    WordModel(
      id: 'w_t8',
      wordOlChiki: 'ᱨᱟᱵᱟᱝ ᱨᱤᱛᱩ',
      wordLatin: 'Rabang ritu',
      meaning: 'Winter',
      category: 'time',
      order: 128,
    ),
    WordModel(
      id: 'w_t9',
      wordOlChiki: 'ᱥᱮᱨᱢᱟ',
      wordLatin: 'Serma',
      meaning: 'Year',
      category: 'time',
      order: 129,
    ),
    WordModel(
      id: 'w_t10',
      wordOlChiki: 'ᱦᱟᱯᱛᱟ',
      wordLatin: 'Hapta',
      meaning: 'Week',
      category: 'time',
      order: 130,
    ),
    WordModel(
      id: 'w_t11',
      wordOlChiki: 'ᱜᱷᱟᱱᱴᱟ',
      wordLatin: 'Ghanta',
      meaning: 'Hour',
      category: 'time',
      order: 131,
    ),
    WordModel(
      id: 'w_t12',
      wordOlChiki: 'ᱴᱤᱲᱤᱡ',
      wordLatin: 'Tirij',
      meaning: 'Minute',
      category: 'time',
      order: 132,
    ),
    WordModel(
      id: 'w_t13',
      wordOlChiki: 'ᱥᱮᱛᱟᱜ',
      wordLatin: 'Setag',
      meaning: 'Morning',
      category: 'time',
      order: 133,
    ),
    WordModel(
      id: 'w_t14',
      wordOlChiki: 'ᱛᱤᱠᱤᱱ',
      wordLatin: 'Tikin',
      meaning: 'Noon',
      category: 'time',
      order: 134,
    ),
    WordModel(
      id: 'w_t15',
      wordOlChiki: 'ᱟᱹᱭᱩᱵ',
      wordLatin: 'Ayub',
      meaning: 'Evening',
      category: 'time',
      order: 135,
    ),
    WordModel(
      id: 'w_t16',
      wordOlChiki: 'ᱧᱤᱫᱟᱹ',
      wordLatin: 'Njida',
      meaning: 'Night',
      category: 'time',
      order: 136,
    ),
    WordModel(
      id: 'w_t17',
      wordOlChiki: 'ᱢᱮᱭᱟᱝ',
      wordLatin: 'Meyang',
      meaning: 'Day after tomorrow',
      category: 'time',
      order: 137,
    ),
    WordModel(
      id: 'w_t18',
      wordOlChiki: 'ᱢᱟᱦᱟᱸᱫᱮᱨ',
      wordLatin: 'Mahander',
      meaning: 'Day before yesterday',
      category: 'time',
      order: 138,
    ),
    WordModel(
      id: 'w_t19',
      wordOlChiki: 'ᱱᱤᱛᱚᱜ',
      wordLatin: 'Nitog',
      meaning: 'Now',
      category: 'time',
      order: 139,
    ),
    WordModel(
      id: 'w_t20',
      wordOlChiki: 'ᱛᱟᱭᱚᱢ',
      wordLatin: 'Tayom',
      meaning: 'Later',
      category: 'time',
      order: 140,
    ),

    // ── Trending & Popular (trending) ──
    WordModel(
      id: 'w_tr1',
      wordOlChiki: 'ᱯᱟᱹᱨᱥᱤ',
      wordLatin: 'Parsi',
      meaning: 'Language',
      category: 'trending',
      order: 141,
    ),
    WordModel(
      id: 'w_tr2',
      wordOlChiki: 'ᱥᱟᱱᱛᱟᱲᱤ',
      wordLatin: 'Santali',
      meaning: 'Santali',
      category: 'trending',
      order: 142,
    ),
    WordModel(
      id: 'w_tr3',
      wordOlChiki: 'ᱚᱞ ᱪᱤᱠᱤ',
      wordLatin: 'Ol Chiki',
      meaning: 'Ol Chiki Script',
      category: 'trending',
      order: 143,
    ),
    WordModel(
      id: 'w_tr4',
      wordOlChiki: 'ᱯᱩᱛᱷᱤ',
      wordLatin: 'Puthi',
      meaning: 'Book',
      category: 'trending',
      order: 144,
    ),
    WordModel(
      id: 'w_tr5',
      wordOlChiki: 'ᱤᱛᱩᱱ ᱟᱥᱲᱟ',
      wordLatin: 'Itun asra',
      meaning: 'School',
      category: 'trending',
      order: 145,
    ),
    WordModel(
      id: 'w_tr6',
      wordOlChiki: 'ᱫᱤᱥᱚᱢ',
      wordLatin: 'Disom',
      meaning: 'Country',
      category: 'trending',
      order: 146,
    ),
    WordModel(
      id: 'w_tr7',
      wordOlChiki: 'ᱦᱚᱲ',
      wordLatin: 'Hor',
      meaning: 'People',
      category: 'trending',
      order: 147,
    ),
    WordModel(
      id: 'w_tr8',
      wordOlChiki: 'ᱥᱮᱨᱮᱧ',
      wordLatin: 'Serenj',
      meaning: 'Song / Sing',
      category: 'trending',
      order: 148,
    ),
    WordModel(
      id: 'w_tr9',
      wordOlChiki: 'ᱮᱱᱮᱡ',
      wordLatin: 'Enej',
      meaning: 'Dance',
      category: 'trending',
      order: 149,
    ),
    WordModel(
      id: 'w_tr10',
      wordOlChiki: 'ᱯᱚᱨᱚᱵ',
      wordLatin: 'Porob',
      meaning: 'Festival',
      category: 'trending',
      order: 150,
    ),
    WordModel(
      id: 'w_tr11',
      wordOlChiki: 'ᱥᱚᱦᱨᱟᱭ',
      wordLatin: 'Sohrae',
      meaning: 'Sohrae Festival',
      category: 'trending',
      order: 151,
    ),
    WordModel(
      id: 'w_tr12',
      wordOlChiki: 'ᱵᱟᱦᱟ',
      wordLatin: 'Baha porob',
      meaning: 'Flower Festival',
      category: 'trending',
      order: 152,
    ),
    WordModel(
      id: 'w_tr13',
      wordOlChiki: 'ᱛᱩᱢᱫᱟᱜ',
      wordLatin: 'Tumdag',
      meaning: 'Madal / Santali Clay Drum',
      category: 'trending',
      order: 153,
    ),
    WordModel(
      id: 'w_tr14',
      wordOlChiki: 'ᱛᱟᱢᱟᱠ',
      wordLatin: 'Tamak',
      meaning: 'Kettle drum',
      category: 'trending',
      order: 154,
    ),
    WordModel(
      id: 'w_tr15',
      wordOlChiki: 'ᱵᱟᱱᱟᱢ',
      wordLatin: 'Banam',
      meaning: 'Fiddle (Santali instrument)',
      category: 'trending',
      order: 155,
    ),
    WordModel(
      id: 'w_tr16',
      wordOlChiki: 'ᱛᱤᱨᱭᱟᱹᱣ',
      wordLatin: 'Tiryaw',
      meaning: 'Flute',
      category: 'trending',
      order: 156,
    ),
    WordModel(
      id: 'w_tr17',
      wordOlChiki: 'ᱡᱟᱹᱛᱤ',
      wordLatin: 'Jati',
      meaning: 'Tribe / Nation',
      category: 'trending',
      order: 157,
    ),
    WordModel(
      id: 'w_tr18',
      wordOlChiki: 'ᱠᱷᱮᱨᱣᱟᱲ',
      wordLatin: 'Kherwar',
      meaning: 'Ancestral name of Santals',
      category: 'trending',
      order: 158,
    ),
    WordModel(
      id: 'w_tr19',
      wordOlChiki: 'ᱥᱟᱶᱦᱮᱫ',
      wordLatin: 'Sawhed',
      meaning: 'Literature',
      category: 'trending',
      order: 159,
    ),
    WordModel(
      id: 'w_tr20',
      wordOlChiki: 'ᱞᱟᱠᱪᱟᱨ',
      wordLatin: 'Lakcar',
      meaning: 'Culture',
      category: 'trending',
      order: 160,
    ),

    // ── Body Parts (body) ──
    WordModel(
      id: 'w_bd1',
      wordOlChiki: 'ᱵᱚᱦᱚᱜ',
      wordLatin: 'Bohog',
      meaning: 'Head',
      category: 'body',
      order: 161,
    ),
    WordModel(
      id: 'w_bd2',
      wordOlChiki: 'ᱤᱞ',
      wordLatin: 'Il',
      meaning: 'Feather',
      category: 'body',
      order: 162,
    ),
    WordModel(
      id: 'w_bd3',
      wordOlChiki: 'ᱚᱞᱚᱝ',
      wordLatin: 'Olong',
      meaning: 'Forehead',
      category: 'body',
      order: 163,
    ),
    WordModel(
      id: 'w_bd4',
      wordOlChiki: 'ᱢᱮᱫ',
      wordLatin: 'Med',
      meaning: 'Eye',
      category: 'body',
      order: 164,
    ),
    WordModel(
      id: 'w_bd5',
      wordOlChiki: 'ᱞᱩᱛᱩᱨ',
      wordLatin: 'Lutur',
      meaning: 'Ear',
      category: 'body',
      order: 165,
    ),
    WordModel(
      id: 'w_bd6',
      wordOlChiki: 'ᱢᱩ',
      wordLatin: 'Mu',
      meaning: 'Nose',
      category: 'body',
      order: 166,
    ),
    WordModel(
      id: 'w_bd7',
      wordOlChiki: 'ᱞᱩᱴᱤ',
      wordLatin: 'Luti',
      meaning: 'Lip',
      category: 'body',
      order: 167,
    ),
    WordModel(
      id: 'w_bd8',
      wordOlChiki: 'ᱟᱞᱟᱝ',
      wordLatin: 'Alang',
      meaning: 'Tongue',
      category: 'body',
      order: 168,
    ),
    WordModel(
      id: 'w_bd9',
      wordOlChiki: 'ᱰᱟᱴᱟ',
      wordLatin: 'Data',
      meaning: 'Tooth',
      category: 'body',
      order: 169,
    ),
    WordModel(
      id: 'w_bd10',
      wordOlChiki: 'ᱦᱚᱛᱚᱛ',
      wordLatin: 'Hotot',
      meaning: 'Throat',
      category: 'body',
      order: 170,
    ),
    WordModel(
      id: 'w_bd11',
      wordOlChiki: 'ᱛᱤ',
      wordLatin: 'Ti',
      meaning: 'Hand / Arm',
      category: 'body',
      order: 171,
    ),
    WordModel(
      id: 'w_bd12',
      wordOlChiki: 'ᱡᱟᱸᱜᱟ',
      wordLatin: 'Janga',
      meaning: 'Leg / Foot',
      category: 'body',
      order: 172,
    ),
    WordModel(
      id: 'w_bd13',
      wordOlChiki: 'ᱠᱚᱲᱟᱢ',
      wordLatin: 'Koram',
      meaning: 'Chest',
      category: 'body',
      order: 173,
    ),
    WordModel(
      id: 'w_bd14',
      wordOlChiki: 'ᱞᱟᱡ',
      wordLatin: 'Laj',
      meaning: 'Stomach',
      category: 'body',
      order: 174,
    ),
    WordModel(
      id: 'w_bd15',
      wordOlChiki: 'ᱫᱮᱭᱟ',
      wordLatin: 'Deya',
      meaning: 'Back',
      category: 'body',
      order: 175,
    ),
    WordModel(
      id: 'w_bd16',
      wordOlChiki: 'ᱩᱵ',
      wordLatin: 'Ub',
      meaning: 'Hair',
      category: 'body',
      order: 176,
    ),
    WordModel(
      id: 'w_bd17',
      wordOlChiki: 'ᱠᱟᱴᱩᱯ',
      wordLatin: 'Katup',
      meaning: 'Finger',
      category: 'body',
      order: 177,
    ),
    WordModel(
      id: 'w_bd18',
      wordOlChiki: 'ᱨᱟᱢᱟ',
      wordLatin: 'Rama',
      meaning: 'Nail',
      category: 'body',
      order: 178,
    ),
    WordModel(
      id: 'w_bd19',
      wordOlChiki: 'ᱦᱟᱨᱛᱟ',
      wordLatin: 'Harta',
      meaning: 'Skin',
      category: 'body',
      order: 179,
    ),
    WordModel(
      id: 'w_bd20',
      wordOlChiki: 'ᱢᱟᱭᱟᱢ',
      wordLatin: 'Mayam',
      meaning: 'Blood',
      category: 'body',
      order: 180,
    ),

    // ── Food (food) ──
    WordModel(
      id: 'w_fd1',
      wordOlChiki: 'ᱫᱟᱠᱟ',
      wordLatin: 'Daka',
      meaning: 'Cooked Rice / Food',
      category: 'food',
      order: 181,
    ),
    WordModel(
      id: 'w_fd2',
      wordOlChiki: 'ᱫᱟᱜ',
      wordLatin: 'Dag',
      meaning: 'Water',
      category: 'food',
      order: 182,
    ),
    WordModel(
      id: 'w_fd3',
      wordOlChiki: 'ᱡᱮᱞ',
      wordLatin: 'Jel',
      meaning: 'Meat',
      category: 'food',
      order: 183,
    ),
    WordModel(
      id: 'w_fd4',
      wordOlChiki: 'ᱦᱟᱹᱠᱩ',
      wordLatin: 'Haku jel',
      meaning: 'Fish',
      category: 'food',
      order: 184,
    ),
    WordModel(
      id: 'w_fd5',
      wordOlChiki: 'ᱩᱛᱩ',
      wordLatin: 'Utu',
      meaning: 'Curry / Vegetables',
      category: 'food',
      order: 185,
    ),
    WordModel(
      id: 'w_fd6',
      wordOlChiki: 'ᱫᱟᱹᱞ',
      wordLatin: 'Dal',
      meaning: 'Lentil / Pulse',
      category: 'food',
      order: 186,
    ),
    WordModel(
      id: 'w_fd7',
      wordOlChiki: 'ᱵᱩᱞᱩᱝ',
      wordLatin: 'Bulung',
      meaning: 'Salt',
      category: 'food',
      order: 187,
    ),
    WordModel(
      id: 'w_fd8',
      wordOlChiki: 'ᱥᱩᱱᱩᱢ',
      wordLatin: 'Sunum',
      meaning: 'Oil',
      category: 'food',
      order: 188,
    ),
    WordModel(
      id: 'w_fd9',
      wordOlChiki: 'ᱢᱟᱹᱨᱤᱪ',
      wordLatin: 'Maric',
      meaning: 'Chili',
      category: 'food',
      order: 189,
    ),
    WordModel(
      id: 'w_fd10',
      wordOlChiki: 'ᱯᱤᱴᱷᱟᱹ',
      wordLatin: 'Pitha',
      meaning: 'Bread / Cake',
      category: 'food',
      order: 190,
    ),
    WordModel(
      id: 'w_fd11',
      wordOlChiki: 'ᱛᱳᱣᱟ',
      wordLatin: 'Towa',
      meaning: 'Milk',
      category: 'food',
      order: 191,
    ),
    WordModel(
      id: 'w_fd12',
      wordOlChiki: 'ᱫᱟᱦᱤ',
      wordLatin: 'Dahi',
      meaning: 'Curd',
      category: 'food',
      order: 192,
    ),
    WordModel(
      id: 'w_fd13',
      wordOlChiki: 'ᱜᱷᱤᱣ',
      wordLatin: 'Ghiw',
      meaning: 'Ghee / Clarified butter',
      category: 'food',
      order: 193,
    ),
    WordModel(
      id: 'w_fd14',
      wordOlChiki: 'ᱡᱚ',
      wordLatin: 'Jo',
      meaning: 'Fruit',
      category: 'food',
      order: 194,
    ),
    WordModel(
      id: 'w_fd15',
      wordOlChiki: 'ᱩᱞ',
      wordLatin: 'Ul',
      meaning: 'Mango',
      category: 'food',
      order: 195,
    ),
    WordModel(
      id: 'w_fd16',
      wordOlChiki: 'ᱠᱟᱭᱨᱟ',
      wordLatin: 'Kayra',
      meaning: 'Banana',
      category: 'food',
      order: 196,
    ),
    WordModel(
      id: 'w_fd17',
      wordOlChiki: 'ᱠᱟᱱᱛᱷᱟᱲ',
      wordLatin: 'Kanthar',
      meaning: 'Jackfruit',
      category: 'food',
      order: 197,
    ),
    WordModel(
      id: 'w_fd18',
      wordOlChiki: 'ᱜᱩᱲ',
      wordLatin: 'Gur',
      meaning: 'Jaggery',
      category: 'food',
      order: 198,
    ),
    WordModel(
      id: 'w_fd19',
      wordOlChiki: 'ᱪᱤᱱᱤ',
      wordLatin: 'Cini',
      meaning: 'Sugar',
      category: 'food',
      order: 199,
    ),
    WordModel(
      id: 'w_fd20',
      wordOlChiki: 'ᱦᱚᱲᱮᱡ',
      wordLatin: 'Horej',
      meaning: 'Black gram beans',
      category: 'food',
      order: 200,
    ),

    WordModel(
      id: 'w_extra_1',
      wordOlChiki: 'ᱢᱟᱨᱟᱝ',
      wordLatin: 'Marang',
      meaning: 'Big / Great',
      category: 'extra',
      order: 201,
    ),
    WordModel(
      id: 'w_extra_2',
      wordOlChiki: 'ᱦᱩᱰᱤᱧ',
      wordLatin: 'Hudinj',
      meaning: 'Small',
      category: 'extra',
      order: 202,
    ),
    WordModel(
      id: 'w_extra_3',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ',
      wordLatin: 'Sagun',
      meaning: 'Auspicious / Good',
      category: 'extra',
      order: 203,
    ),
    WordModel(
      id: 'w_extra_4',
      wordOlChiki: 'ᱱᱟᱯᱟᱭ',
      wordLatin: 'Napay',
      meaning: 'Fine / Good',
      category: 'extra',
      order: 204,
    ),
    WordModel(
      id: 'w_extra_5',
      wordOlChiki: 'ᱧᱩᱛᱩᱢ',
      wordLatin: 'Nyutum',
      meaning: 'Name',
      category: 'extra',
      order: 205,
    ),
    WordModel(
      id: 'w_extra_6',
      wordOlChiki: 'ᱡᱩᱢᱤᱫᱽ',
      wordLatin: 'Jumid',
      meaning: 'Unity',
      category: 'extra',
      order: 206,
    ),
    WordModel(
      id: 'w_extra_7',
      wordOlChiki: 'ᱜᱚᱝᱜᱚ',
      wordLatin: 'Gongo',
      meaning: 'Uncle (father\'s elder brother)',
      category: 'extra',
      order: 207,
    ),
    WordModel(
      id: 'w_extra_8',
      wordOlChiki: 'ᱵᱮᱴᱟ',
      wordLatin: 'Beta',
      meaning: 'Son',
      category: 'extra',
      order: 208,
    ),
    WordModel(
      id: 'w_extra_9',
      wordOlChiki: 'ᱵᱤᱴᱤ',
      wordLatin: 'Biti',
      meaning: 'Daughter',
      category: 'extra',
      order: 209,
    ),
    WordModel(
      id: 'w_extra_10',
      wordOlChiki: 'ᱜᱟᱛᱮ',
      wordLatin: 'Gate',
      meaning: 'Friend',
      category: 'extra',
      order: 210,
    ),
    WordModel(
      id: 'w_extra_11',
      wordOlChiki: 'ᱡᱚᱢ',
      wordLatin: 'Jom',
      meaning: 'Eat',
      category: 'extra',
      order: 211,
    ),
    WordModel(
      id: 'w_extra_12',
      wordOlChiki: 'ᱧᱩ',
      wordLatin: 'Nju',
      meaning: 'Drink',
      category: 'extra',
      order: 212,
    ),
    WordModel(
      id: 'w_extra_13',
      wordOlChiki: 'ᱜᱤᱛᱤᱡ',
      wordLatin: 'Gitij',
      meaning: 'Sleep',
      category: 'extra',
      order: 213,
    ),
    WordModel(
      id: 'w_extra_14',
      wordOlChiki: 'ᱪᱟᱞᱟᱜ',
      wordLatin: 'Chalag',
      meaning: 'Go',
      category: 'extra',
      order: 214,
    ),
    WordModel(
      id: 'w_extra_15',
      wordOlChiki: 'ᱯᱟᱲᱦᱟᱣ',
      wordLatin: 'Parhaw',
      meaning: 'Read / Study',
      category: 'extra',
      order: 215,
    ),
    WordModel(
      id: 'w_extra_16',
      wordOlChiki: 'ᱞᱟᱸᱫᱟ',
      wordLatin: 'Landa',
      meaning: 'Laugh',
      category: 'extra',
      order: 216,
    ),
    WordModel(
      id: 'w_extra_17',
      wordOlChiki: 'ᱞᱩᱢᱟᱹᱝ',
      wordLatin: 'Lumang',
      meaning: 'Golden / Silk color',
      category: 'extra',
      order: 217,
    ),
    WordModel(
      id: 'w_extra_18',
      wordOlChiki: 'ᱦᱟᱥᱟ ᱨᱚᱝ',
      wordLatin: 'Hasa rong',
      meaning: 'Brown / Mud color',
      category: 'extra',
      order: 218,
    ),
    WordModel(
      id: 'w_extra_19',
      wordOlChiki: 'ᱜᱩᱞᱟᱹᱯ',
      wordLatin: 'Gulap',
      meaning: 'Pink',
      category: 'extra',
      order: 219,
    ),
    WordModel(
      id: 'w_extra_20',
      wordOlChiki: 'ᱵᱮᱸᱜᱟᱲ',
      wordLatin: 'Bengad',
      meaning: 'Purple / Eggplant color',
      category: 'extra',
      order: 220,
    ),
    WordModel(
      id: 'w_extra_21',
      wordOlChiki: 'ᱪᱟᱸᱫᱚ ᱨᱚᱝ',
      wordLatin: 'Chando rong',
      meaning: 'Silver / Moon color',
      category: 'extra',
      order: 221,
    ),
    WordModel(
      id: 'w_extra_22',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ ᱨᱚᱝ',
      wordLatin: 'Sengel rong',
      meaning: 'Orange / Fire color',
      category: 'extra',
      order: 222,
    ),
    WordModel(
      id: 'w_extra_23',
      wordOlChiki: 'ᱥᱟᱠᱟᱢ ᱨᱚᱝ',
      wordLatin: 'Sakam rong',
      meaning: 'Leaf green',
      category: 'extra',
      order: 223,
    ),
    WordModel(
      id: 'w_extra_24',
      wordOlChiki: 'ᱥᱤᱨᱢᱟ ᱨᱚᱝ',
      wordLatin: 'Sirma rong',
      meaning: 'Sky blue',
      category: 'extra',
      order: 224,
    ),
    WordModel(
      id: 'w_extra_25',
      wordOlChiki: 'ᱢᱮᱫ ᱨᱚᱝ',
      wordLatin: 'Med rong',
      meaning: 'Eye color',
      category: 'extra',
      order: 225,
    ),
    WordModel(
      id: 'w_extra_26',
      wordOlChiki: 'ᱞᱟᱨ',
      wordLatin: 'Lar',
      meaning: 'Indigo',
      category: 'extra',
      order: 226,
    ),
    WordModel(
      id: 'w_extra_27',
      wordOlChiki: 'ᱪᱚᱢᱠᱟᱣ',
      wordLatin: 'Comkaw',
      meaning: 'Shiny / Bright',
      category: 'extra',
      order: 227,
    ),
    WordModel(
      id: 'w_extra_28',
      wordOlChiki: 'ᱢᱤᱞᱚᱱ',
      wordLatin: 'Milon',
      meaning: 'Mixed color',
      category: 'extra',
      order: 228,
    ),
    WordModel(
      id: 'w_extra_29',
      wordOlChiki: 'ᱠᱷᱟᱹᱱᱰᱤᱭᱟᱹ',
      wordLatin: 'Khandiya',
      meaning: 'Dark shade / Grey',
      category: 'extra',
      order: 229,
    ),
    WordModel(
      id: 'w_extra_30',
      wordOlChiki: 'ᱠᱩᱞ',
      wordLatin: 'Kul',
      meaning: 'Lion',
      category: 'extra',
      order: 230,
    ),
    WordModel(
      id: 'w_extra_31',
      wordOlChiki: 'ᱵᱷᱤᱰᱤ',
      wordLatin: 'Bhidi',
      meaning: 'Sheep',
      category: 'extra',
      order: 231,
    ),
    WordModel(
      id: 'w_extra_32',
      wordOlChiki: 'ᱥᱩᱠᱨᱤ',
      wordLatin: 'Sukri',
      meaning: 'Pig',
      category: 'extra',
      order: 232,
    ),
    WordModel(
      id: 'w_extra_33',
      wordOlChiki: 'ᱥᱤᱢ',
      wordLatin: 'Sim',
      meaning: 'Chicken / Hen',
      category: 'extra',
      order: 233,
    ),
    WordModel(
      id: 'w_extra_34',
      wordOlChiki: 'ᱥᱤᱸᱜᱮ',
      wordLatin: 'Singe',
      meaning: 'Sun',
      category: 'extra',
      order: 234,
    ),
    WordModel(
      id: 'w_extra_35',
      wordOlChiki: 'ᱚᱠᱛᱚ',
      wordLatin: 'Okto',
      meaning: 'Time',
      category: 'extra',
      order: 235,
    ),
    WordModel(
      id: 'w_extra_36',
      wordOlChiki: 'ᱴᱤᱠᱤᱱ',
      wordLatin: 'Tikin',
      meaning: 'Noon',
      category: 'extra',
      order: 236,
    ),
    WordModel(
      id: 'w_extra_37',
      wordOlChiki: 'ᱥᱤᱸᱜᱮ ᱢᱟᱦᱟ',
      wordLatin: 'Singe maha',
      meaning: 'Sunday',
      category: 'extra',
      order: 237,
    ),
    WordModel(
      id: 'w_extra_38',
      wordOlChiki: 'ᱚᱛᱮ ᱢᱟᱦᱟ',
      wordLatin: 'Ote maha',
      meaning: 'Monday',
      category: 'extra',
      order: 238,
    ),
    WordModel(
      id: 'w_extra_39',
      wordOlChiki: 'ᱵᱟᱞᱮ ᱢᱟᱦᱟ',
      wordLatin: 'Bale maha',
      meaning: 'Tuesday',
      category: 'extra',
      order: 239,
    ),
    WordModel(
      id: 'w_extra_40',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱢᱟᱦᱟ',
      wordLatin: 'Sagun maha',
      meaning: 'Wednesday',
      category: 'extra',
      order: 240,
    ),
    WordModel(
      id: 'w_extra_41',
      wordOlChiki: 'ᱥᱟᱹᱨᱫᱤ ᱢᱟᱦᱟ',
      wordLatin: 'Sardi maha',
      meaning: 'Thursday',
      category: 'extra',
      order: 241,
    ),
    WordModel(
      id: 'w_extra_42',
      wordOlChiki: 'ᱡᱟᱹᱨᱩᱢ ᱢᱟᱦᱟ',
      wordLatin: 'Jarum maha',
      meaning: 'Friday',
      category: 'extra',
      order: 242,
    ),
    WordModel(
      id: 'w_extra_43',
      wordOlChiki: 'ᱜᱩᱨᱩ ᱠᱚᱞᱚᱢ',
      wordLatin: 'Guru kolom',
      meaning: 'Guru\'s Pen / Scholar',
      category: 'extra',
      order: 243,
    ),
    WordModel(
      id: 'w_extra_44',
      wordOlChiki: 'ᱥᱮᱪᱮᱫ',
      wordLatin: 'Seched',
      meaning: 'Education',
      category: 'extra',
      order: 244,
    ),
    WordModel(
      id: 'w_extra_45',
      wordOlChiki: 'ᱥᱚᱢᱟᱡᱽ',
      wordLatin: 'Somaj',
      meaning: 'Society',
      category: 'extra',
      order: 245,
    ),
    WordModel(
      id: 'w_extra_46',
      wordOlChiki: 'ᱟᱹᱨᱤ ᱪᱟᱹᱞᱤ',
      wordLatin: 'Ari chali',
      meaning: 'Customs',
      category: 'extra',
      order: 246,
    ),
    WordModel(
      id: 'w_extra_47',
      wordOlChiki: 'ᱵᱤᱪᱟᱹᱨ',
      wordLatin: 'Bicar',
      meaning: 'Justice / Discussion',
      category: 'extra',
      order: 247,
    ),
    WordModel(
      id: 'w_extra_48',
      wordOlChiki: 'ᱜᱟᱛᱮ ᱠᱚ',
      wordLatin: 'Gate ko',
      meaning: 'Friends',
      category: 'extra',
      order: 248,
    ),
    WordModel(
      id: 'w_extra_49',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱫᱷᱚᱨᱚᱢ',
      wordLatin: 'Sari dhorom',
      meaning: 'Truth path / Traditional religion',
      category: 'extra',
      order: 249,
    ),
    WordModel(
      id: 'w_extra_50',
      wordOlChiki: 'ᱨᱟᱹᱥᱠᱟᱹ',
      wordLatin: 'Raska',
      meaning: 'Joy / Happiness',
      category: 'extra',
      order: 250,
    ),
    WordModel(
      id: 'w_extra_51',
      wordOlChiki: 'ᱥᱟᱨᱦᱟᱣ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Sarhaw katha',
      meaning: 'Words of appreciation',
      category: 'extra',
      order: 251,
    ),
    WordModel(
      id: 'w_extra_52',
      wordOlChiki: 'ᱡᱟᱦᱮᱨ ᱛᱷᱟᱱ',
      wordLatin: 'Jaher than',
      meaning: 'Sacred grove',
      category: 'extra',
      order: 252,
    ),
    WordModel(
      id: 'w_extra_53',
      wordOlChiki: 'ᱦᱚᱲ ᱦᱚᱯᱚᱱ',
      wordLatin: 'Hor hopon',
      meaning: 'Santal people',
      category: 'extra',
      order: 253,
    ),
    WordModel(
      id: 'w_extra_54',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Sari katha',
      meaning: 'Truth / True words',
      category: 'extra',
      order: 254,
    ),
    WordModel(
      id: 'w_extra_55',
      wordOlChiki: 'ᱥᱤᱵᱤᱞ ᱨᱚᱲ',
      wordLatin: 'Sibil ror',
      meaning: 'Gentle speech / Kind words',
      category: 'extra',
      order: 255,
    ),
    WordModel(
      id: 'w_extra_56',
      wordOlChiki: 'ᱠᱟᱹᱢᱤ ᱜᱮ ᱫᱷᱚᱨᱚᱢ',
      wordLatin: 'Kami ge dhorom',
      meaning: 'Work is worship',
      category: 'extra',
      order: 256,
    ),
    WordModel(
      id: 'w_extra_57',
      wordOlChiki: 'ᱫᱤᱥᱚᱢ ᱫᱩᱞᱟᱹᱲ',
      wordLatin: 'Disom dular',
      meaning: 'Patriotism / Country love',
      category: 'extra',
      order: 257,
    ),
    WordModel(
      id: 'w_extra_58',
      wordOlChiki: 'ᱫᱷᱤᱨᱤ',
      wordLatin: 'Dhiri',
      meaning: 'Stone',
      category: 'extra',
      order: 258,
    ),
    WordModel(
      id: 'w_extra_59',
      wordOlChiki: 'ᱜᱤᱛᱤᱞ',
      wordLatin: 'Gitil',
      meaning: 'Sand',
      category: 'extra',
      order: 259,
    ),
    WordModel(
      id: 'w_extra_60',
      wordOlChiki: 'ᱚᱛ',
      wordLatin: 'Ot',
      meaning: 'Earth / Ground',
      category: 'extra',
      order: 260,
    ),
    WordModel(
      id: 'w_extra_61',
      wordOlChiki: 'ᱵᱤᱨ',
      wordLatin: 'Bir',
      meaning: 'Forest',
      category: 'extra',
      order: 261,
    ),
    WordModel(
      id: 'w_extra_62',
      wordOlChiki: 'ᱵᱩᱨᱩ',
      wordLatin: 'Buru',
      meaning: 'Mountain / Hill',
      category: 'extra',
      order: 262,
    ),
    WordModel(
      id: 'w_extra_63',
      wordOlChiki: 'ᱜᱟᱰᱟ',
      wordLatin: 'Gada',
      meaning: 'River',
      category: 'extra',
      order: 263,
    ),
    WordModel(
      id: 'w_extra_64',
      wordOlChiki: 'ᱡᱷᱟᱨᱱᱟ',
      wordLatin: 'Jharna',
      meaning: 'Spring / Waterfall',
      category: 'extra',
      order: 264,
    ),
    WordModel(
      id: 'w_extra_65',
      wordOlChiki: 'ᱥᱟᱦᱟᱱ',
      wordLatin: 'Sahan',
      meaning: 'Firewood',
      category: 'extra',
      order: 265,
    ),
    WordModel(
      id: 'w_extra_66',
      wordOlChiki: 'ᱢᱮᱫ ᱞᱩᱴᱩᱨ ᱵᱮᱸᱜᱮᱫ',
      wordLatin: 'Med lutur benget',
      meaning: 'Keeping eyes and ears open / Vigilant',
      category: 'extra',
      order: 266,
    ),
    WordModel(
      id: 'w_extra_67',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱞᱟᱰᱮ',
      wordLatin: 'Mone lade',
      meaning: 'Discouraged / Dejected',
      category: 'extra',
      order: 267,
    ),
    WordModel(
      id: 'w_extra_68',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱡᱟᱞᱟ',
      wordLatin: 'Jiwi jala',
      meaning: 'Life struggles',
      category: 'extra',
      order: 268,
    ),
    WordModel(
      id: 'w_extra_69',
      wordOlChiki: 'ᱫᱟᱨᱮ ᱩᱢᱩᱞ ᱦᱚᱲ ᱩᱢᱩᱞ',
      wordLatin: 'Dare umul hor umul',
      meaning: 'Protection of elders / Family shelter',
      category: 'extra',
      order: 269,
    ),
    WordModel(
      id: 'w_extra_70',
      wordOlChiki: 'ᱥᱮᱛᱟ ᱡᱷᱟᱹᱞᱤ ᱞᱮᱠᱟ',
      wordLatin: 'Seta jhale leka',
      meaning: 'Entangled in trouble / Trapped',
      category: 'extra',
      order: 270,
    ),
    WordModel(
      id: 'w_extra_71',
      wordOlChiki: 'ᱢᱟᱹᱱᱢᱤ ᱡᱤᱣᱤ',
      wordLatin: 'Manmi jiwi',
      meaning: 'Human life',
      category: 'extra',
      order: 271,
    ),
    WordModel(
      id: 'w_extra_72',
      wordOlChiki: 'ᱢᱟᱹᱱ ᱥᱟᱨᱦᱟᱣ',
      wordLatin: 'Man sarhaw',
      meaning: 'Respect and praise',
      category: 'extra',
      order: 272,
    ),
    WordModel(
      id: 'w_extra_73',
      wordOlChiki: 'ᱞᱟᱜᱽᱬᱮ',
      wordLatin: 'Lagne',
      meaning: 'Traditional Santal dance',
      category: 'extra',
      order: 273,
    ),
    WordModel(
      id: 'w_extra_74',
      wordOlChiki: 'ᱫᱚᱝ',
      wordLatin: 'Dong',
      meaning: 'Marriage dance and song genre',
      category: 'extra',
      order: 274,
    ),
    WordModel(
      id: 'w_extra_75',
      wordOlChiki: 'ᱴᱟᱢᱟᱠ',
      wordLatin: 'Tamak',
      meaning: 'Kettle drum',
      category: 'extra',
      order: 275,
    ),
    WordModel(
      id: 'w_extra_76',
      wordOlChiki: 'ᱛᱤᱨᱭᱳ',
      wordLatin: 'Tiryo',
      meaning: 'Bamboo flute',
      category: 'extra',
      order: 276,
    ),
    WordModel(
      id: 'w_extra_77',
      wordOlChiki: 'ᱥᱟᱨᱡᱚᱢ',
      wordLatin: 'Sarjom',
      meaning: 'Sal tree (sacred to Santals)',
      category: 'extra',
      order: 277,
    ),
    WordModel(
      id: 'w_extra_78',
      wordOlChiki: 'ᱢᱟᱹᱛᱠᱟᱹᱢ',
      wordLatin: 'Matkam',
      meaning: 'Mahua flower/fruit',
      category: 'extra',
      order: 278,
    ),
    WordModel(
      id: 'w_extra_79',
      wordOlChiki: 'ᱡᱚᱦᱟᱨ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Johar katha',
      meaning: 'Welcoming words',
      category: 'extra',
      order: 279,
    ),
    WordModel(
      id: 'w_extra_80',
      wordOlChiki: 'ᱠᱩᱞᱦᱤ',
      wordLatin: 'Kulhi',
      meaning: 'Village street',
      category: 'extra',
      order: 280,
    ),
    WordModel(
      id: 'w_extra_81',
      wordOlChiki: 'ᱢᱟᱹᱧᱡᱷᱤ ᱛᱷᱟᱱ',
      wordLatin: 'Manjhi than',
      meaning: 'Village headman\'s altar',
      category: 'extra',
      order: 281,
    ),
    WordModel(
      id: 'w_extra_82',
      wordOlChiki: 'ᱟᱹᱛᱩ ᱦᱚᱲ',
      wordLatin: 'Atu hor',
      meaning: 'Villagers',
      category: 'extra',
      order: 282,
    ),
    WordModel(
      id: 'w_extra_83',
      wordOlChiki: 'ᱦᱟᱲᱟᱢ ᱵᱩᱰᱷᱤ',
      wordLatin: 'Haram budhi',
      meaning: 'Ancestors / Old couple',
      category: 'extra',
      order: 283,
    ),
    WordModel(
      id: 'w_extra_84',
      wordOlChiki: 'ᱫᱟᱠᱟ ᱩᱛᱩ',
      wordLatin: 'Daka utu',
      meaning: 'Rice and curry / Meal',
      category: 'extra',
      order: 284,
    ),
    WordModel(
      id: 'w_extra_85',
      wordOlChiki: 'ᱞᱩᱴᱤ ᱪᱩᱭᱞᱩ',
      wordLatin: 'Luti chuylu',
      meaning: 'Sulking / Pouting in anger',
      category: 'extra',
      order: 285,
    ),
    WordModel(
      id: 'w_extra_86',
      wordOlChiki: 'ᱢᱩ ᱛᱮ ᱦᱚᱭ ᱚᱰᱚᱠ',
      wordLatin: 'Mu te hoy odok',
      meaning: 'Snorting in rage / Proud',
      category: 'extra',
      order: 286,
    ),
    WordModel(
      id: 'w_extra_87',
      wordOlChiki: 'ᱫᱟᱜ ᱨᱮ ᱡᱷᱟᱹᱞᱤ ᱵᱟᱹᱭᱥᱟᱹᱣ',
      wordLatin: 'Dag re jhale baysaw',
      meaning: 'Chasing shadows / Setting net in water',
      category: 'extra',
      order: 287,
    ),
    WordModel(
      id: 'w_extra_88',
      wordOlChiki: 'ᱫᱟᱨᱮ ᱜᱮ ᱡᱤᱣᱤ',
      wordLatin: 'Dare ge jiwi',
      meaning: 'Trees are life / Environmental wisdom',
      category: 'extra',
      order: 288,
    ),
    WordModel(
      id: 'w_extra_89',
      wordOlChiki: 'ᱜᱚᱡ ᱦᱚᱲ ᱫᱚ ᱵᱟᱹᱠᱩ ᱨᱚᱲᱟ',
      wordLatin: 'Goj hor do baku rora',
      meaning: 'Dead people do not speak / Let bygones be bygones',
      category: 'extra',
      order: 289,
    ),
    WordModel(
      id: 'w_extra_90',
      wordOlChiki: 'ᱟᱹᱛᱩ ᱦᱚᱲ ᱜᱮ ᱫᱤᱥᱚᱢ ᱦᱚᱲ',
      wordLatin: 'Atu hor ge disom hor',
      meaning: 'Village community is the country\'s strength',
      category: 'extra',
      order: 290,
    ),
    WordModel(
      id: 'w_extra_91',
      wordOlChiki: 'ᱢᱮᱫ ᱠᱷᱚᱱ ᱫᱟᱜ ᱡᱚᱨᱚ',
      wordLatin: 'Med khon dag joro',
      meaning: 'Weeping bitterly / Deep grief',
      category: 'extra',
      order: 291,
    ),
    WordModel(
      id: 'w_extra_92',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱵᱟᱹᱲᱤᱡ',
      wordLatin: 'Mone barij',
      meaning: 'Feel sad / Heart-broken',
      category: 'extra',
      order: 292,
    ),
    WordModel(
      id: 'w_extra_93',
      wordOlChiki: 'ᱫᱩᱞᱟᱹᱲ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Dular katha',
      meaning: 'Loving words / Kind speech',
      category: 'extra',
      order: 293,
    ),
    WordModel(
      id: 'w_extra_94',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱫᱷᱚᱱ',
      wordLatin: 'Jiwi dhon',
      meaning: 'Wealth of life / Beloved',
      category: 'extra',
      order: 294,
    ),
    WordModel(
      id: 'w_extra_95',
      wordOlChiki: 'ᱫᱤᱥᱚᱢ ᱫᱟᱨᱟᱱ',
      wordLatin: 'Disom daran',
      meaning: 'Traveling / Exploring the land',
      category: 'extra',
      order: 295,
    ),
    WordModel(
      id: 'w_extra_96',
      wordOlChiki: 'ᱫᱷᱚᱨᱚᱢ ᱠᱟᱹᱢᱤ',
      wordLatin: 'Dhorom kami',
      meaning: 'Righteous deed / Virtuous work',
      category: 'extra',
      order: 296,
    ),
    WordModel(
      id: 'w_extra_97',
      wordOlChiki: 'ᱥᱚᱦᱨᱟᱭ ᱯᱚᱨᱚᱵ',
      wordLatin: 'Sohrae porob',
      meaning: 'Harvest festival / Sohrae',
      category: 'extra',
      order: 297,
    ),
    WordModel(
      id: 'w_extra_98',
      wordOlChiki: 'ᱵᱟᱦᱟ ᱯᱚᱨᱚᱵ',
      wordLatin: 'Baha porob',
      meaning: 'Spring festival / Flower festival',
      category: 'extra',
      order: 298,
    ),
    WordModel(
      id: 'w_extra_99',
      wordOlChiki: 'ᱥᱟᱱᱛᱟᱲᱤ ᱥᱟᱶᱦᱮᱫ',
      wordLatin: 'Santali sawhet',
      meaning: 'Santali literature',
      category: 'extra',
      order: 299,
    ),
    WordModel(
      id: 'w_extra_100',
      wordOlChiki: 'ᱚᱞᱚᱜ ᱯᱟᱲᱦᱟᱣ',
      wordLatin: 'Olog parhaw',
      meaning: 'Education / Learning',
      category: 'extra',
      order: 300,
    ),
    WordModel(
      id: 'w_extra_101',
      wordOlChiki: 'ᱜᱮᱭᱟᱱ ᱦᱚᱨ',
      wordLatin: 'Geyan hor',
      meaning: 'Path of knowledge',
      category: 'extra',
      order: 301,
    ),
    WordModel(
      id: 'w_extra_102',
      wordOlChiki: 'ᱦᱮᱲᱮᱢ ᱨᱚᱲ',
      wordLatin: 'Herem ror',
      meaning: 'Sweet words / Fluent speech',
      category: 'extra',
      order: 302,
    ),
    WordModel(
      id: 'w_extra_103',
      wordOlChiki: 'ᱥᱤᱨᱡᱚᱱᱤᱭᱟᱹ',
      wordLatin: 'Sirjoniya',
      meaning: 'Creator / Nature',
      category: 'extra',
      order: 303,
    ),
    WordModel(
      id: 'w_extra_104',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱠᱷᱮᱞ',
      wordLatin: 'Mone khel',
      meaning: 'Mind game / Flirting',
      category: 'extra',
      order: 304,
    ),
    WordModel(
      id: 'w_extra_105',
      wordOlChiki: 'ᱨᱚᱲ ᱛᱮ ᱞᱟᱸᱫᱟ',
      wordLatin: 'Ror te landa',
      meaning: 'Smiling through words / Sarcasm',
      category: 'extra',
      order: 305,
    ),
    WordModel(
      id: 'w_extra_106',
      wordOlChiki: 'ᱫᱩᱞᱟᱹᱲ ᱡᱟᱹᱞᱤ',
      wordLatin: 'Dular jhale',
      meaning: 'Love trap',
      category: 'extra',
      order: 306,
    ),
    WordModel(
      id: 'w_extra_107',
      wordOlChiki: 'ᱦᱚᱲ ᱥᱟᱢᱟᱝ',
      wordLatin: 'Hor samang',
      meaning: 'Public / In front of people',
      category: 'extra',
      order: 307,
    ),
    WordModel(
      id: 'w_extra_108',
      wordOlChiki: 'ᱞᱩᱴᱤ ᱞᱟᱲᱟᱣ',
      wordLatin: 'Luti laraw',
      meaning: 'Chatting / Gossip',
      category: 'extra',
      order: 308,
    ),
    WordModel(
      id: 'w_extra_109',
      wordOlChiki: 'ᱠᱟᱛᱷᱟ ᱠᱤᱨᱤᱧ',
      wordLatin: 'Katha kirinj',
      meaning: 'Buying words / Accepting advice',
      category: 'extra',
      order: 309,
    ),
    WordModel(
      id: 'w_extra_110',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱞᱚ',
      wordLatin: 'Jiwi lo',
      meaning: 'Heartburn / Jealousy',
      category: 'extra',
      order: 310,
    ),
    WordModel(
      id: 'w_extra_111',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱚᱞ',
      wordLatin: 'Mone ol',
      meaning: 'Writing on heart / Deeply remembering',
      category: 'extra',
      order: 311,
    ),
    WordModel(
      id: 'w_extra_112',
      wordOlChiki: 'ᱢᱮᱫ ᱫᱟᱜ',
      wordLatin: 'Med dag',
      meaning: 'Tears',
      category: 'extra',
      order: 312,
    ),
    WordModel(
      id: 'w_extra_113',
      wordOlChiki: 'ᱞᱟᱸᱫᱟ ᱛᱮ ᱜᱚᱡ',
      wordLatin: 'Landa te goj',
      meaning: 'Dying of laughter',
      category: 'extra',
      order: 313,
    ),
    WordModel(
      id: 'w_extra_114',
      wordOlChiki: 'ᱠᱩᱲᱤ ᱦᱚᱯᱚᱱ',
      wordLatin: 'Kuri hopon',
      meaning: 'Women / Girls',
      category: 'extra',
      order: 314,
    ),
    WordModel(
      id: 'w_extra_115',
      wordOlChiki: 'ᱠᱚᱲᱟ ᱦᱚᱯᱚᱱ',
      wordLatin: 'Kora hopon',
      meaning: 'Men / Boys',
      category: 'extra',
      order: 315,
    ),
    WordModel(
      id: 'w_extra_116',
      wordOlChiki: 'ᱜᱟᱛᱮ ᱠᱩᱲᱤ',
      wordLatin: 'Gate kuri',
      meaning: 'Female friend',
      category: 'extra',
      order: 316,
    ),
    WordModel(
      id: 'w_extra_117',
      wordOlChiki: 'ᱜᱟᱛᱮ ᱠᱚᱲᱟ',
      wordLatin: 'Gate kora',
      meaning: 'Male friend',
      category: 'extra',
      order: 317,
    ),
    WordModel(
      id: 'w_extra_118',
      wordOlChiki: 'ᱜᱩᱯᱩᱛᱤ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Guputi katha',
      meaning: 'Secret talk / Whisper',
      category: 'extra',
      order: 318,
    ),
    WordModel(
      id: 'w_extra_119',
      wordOlChiki: 'ᱨᱟᱹᱥᱠᱟᱹ ᱢᱚᱱᱮ',
      wordLatin: 'Raska mone',
      meaning: 'Joyful mind / Happy heart',
      category: 'extra',
      order: 319,
    ),
    WordModel(
      id: 'w_extra_120',
      wordOlChiki: 'ᱫᱩᱠᱷ ᱡᱤᱣᱤ',
      wordLatin: 'Dukh jiwi',
      meaning: 'Sorrowful life',
      category: 'extra',
      order: 320,
    ),
    WordModel(
      id: 'w_extra_121',
      wordOlChiki: 'ᱦᱚᱲ ᱢᱚᱱᱮ',
      wordLatin: 'Hor mone',
      meaning: 'Public opinion / Human heart',
      category: 'extra',
      order: 321,
    ),
    WordModel(
      id: 'w_extra_122',
      wordOlChiki: 'ᱥᱤᱵᱤᱞ ᱡᱚᱢ',
      wordLatin: 'Sibil jom',
      meaning: 'Delicious food',
      category: 'extra',
      order: 322,
    ),
    WordModel(
      id: 'w_extra_123',
      wordOlChiki: 'ᱫᱟᱲᱮ ᱩᱫᱩᱜ',
      wordLatin: 'Dare udug',
      meaning: 'Show of strength',
      category: 'extra',
      order: 323,
    ),
    WordModel(
      id: 'w_extra_124',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱴᱷᱟᱶ',
      wordLatin: 'Mone thaw',
      meaning: 'Settled mind / Contentment',
      category: 'extra',
      order: 324,
    ),
    WordModel(
      id: 'w_extra_125',
      wordOlChiki: 'ᱨᱚᱲ ᱞᱟᱹᱱᱟᱹᱭ',
      wordLatin: 'Ror lanay',
      meaning: 'Reply / Answer',
      category: 'extra',
      order: 325,
    ),
    WordModel(
      id: 'w_extra_126',
      wordOlChiki: 'ᱫᱤᱱᱟᱹᱢ ᱠᱟᱹᱢᱤ',
      wordLatin: 'Dinam kami',
      meaning: 'Daily chore',
      category: 'extra',
      order: 326,
    ),
    WordModel(
      id: 'w_extra_127',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱢᱚᱱᱮ',
      wordLatin: 'Sari mone',
      meaning: 'Honest heart',
      category: 'extra',
      order: 327,
    ),
    WordModel(
      id: 'w_extra_128',
      wordOlChiki: 'ᱢᱮᱫ ᱞᱩᱞᱩ',
      wordLatin: 'Med lulu',
      meaning: 'Staring blankly / Daydreaming',
      category: 'extra',
      order: 328,
    ),
    WordModel(
      id: 'w_extra_129',
      wordOlChiki: 'ᱞᱩᱴᱩᱨ ᱠᱷᱟᱲᱟ',
      wordLatin: 'Lutur khara',
      meaning: 'Pricking ears / Listening intently',
      category: 'extra',
      order: 329,
    ),
    WordModel(
      id: 'w_extra_130',
      wordOlChiki: 'ᱠᱟᱛᱷᱟ ᱨᱟᱹᱯᱩᱫ',
      wordLatin: 'Katha rapud',
      meaning: 'Breaking words / Interrupting',
      category: 'extra',
      order: 330,
    ),
    WordModel(
      id: 'w_extra_131',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱦᱟᱹᱴᱤᱧ',
      wordLatin: 'Mone hatinj',
      meaning: 'Sharing feelings / Divided mind',
      category: 'extra',
      order: 331,
    ),
    WordModel(
      id: 'w_extra_132',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱡᱩᱞ',
      wordLatin: 'Jiwi jul',
      meaning: 'Burning life / Passionate / Angry',
      category: 'extra',
      order: 332,
    ),
    WordModel(
      id: 'w_extra_133',
      wordOlChiki: 'ᱞᱟᱸᱫᱟ ᱛᱷᱚᱠ',
      wordLatin: 'Landa thok',
      meaning: 'Weary of laughing',
      category: 'extra',
      order: 333,
    ),
    WordModel(
      id: 'w_extra_134',
      wordOlChiki: 'ᱨᱚᱲ ᱪᱮᱦᱨᱟ',
      wordLatin: 'Ror chehra',
      meaning: 'Beautiful speech',
      category: 'extra',
      order: 334,
    ),
    WordModel(
      id: 'w_extra_135',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱫᱟᱲᱮ',
      wordLatin: 'Mone dare',
      meaning: 'Willpower / Mental strength',
      category: 'extra',
      order: 335,
    ),
    WordModel(
      id: 'w_extra_136',
      wordOlChiki: 'ᱥᱟᱹᱜᱟᱹᱭ ᱛᱚᱞ',
      wordLatin: 'Sagay tol',
      meaning: 'Binding relationship / Making friends',
      category: 'extra',
      order: 336,
    ),
    WordModel(
      id: 'w_extra_137',
      wordOlChiki: 'ᱠᱟᱛᱷᱟ ᱛᱚᱞ',
      wordLatin: 'Katha tol',
      meaning: 'Finalizing a promise',
      category: 'extra',
      order: 337,
    ),
    WordModel(
      id: 'w_extra_138',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱨᱟᱲᱟ',
      wordLatin: 'Mone rara',
      meaning: 'Relieved / Free mind',
      category: 'extra',
      order: 338,
    ),
    WordModel(
      id: 'w_extra_139',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱛᱟᱦᱮᱸᱱ',
      wordLatin: 'Jiwi tahen',
      meaning: 'Staying alive / Living well',
      category: 'extra',
      order: 339,
    ),
    WordModel(
      id: 'w_extra_140',
      wordOlChiki: 'ᱫᱩᱞᱟᱹᱲ ᱜᱟᱛᱮ',
      wordLatin: 'Dular gate',
      meaning: 'Sweetheart / Dear friend',
      category: 'extra',
      order: 340,
    ),
    WordModel(
      id: 'w_extra_141',
      wordOlChiki: 'ᱦᱚᱲ ᱦᱚᱨ',
      wordLatin: 'Hor hor',
      meaning: 'Human path / Way of life',
      category: 'extra',
      order: 341,
    ),
    WordModel(
      id: 'w_extra_142',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱥᱟᱨᱦᱟᱣ',
      wordLatin: 'Sari sarhaw',
      meaning: 'True appreciation',
      category: 'extra',
      order: 342,
    ),
    WordModel(
      id: 'w_extra_143',
      wordOlChiki: 'ᱨᱚᱲ ᱞᱟᱹᱰᱩ',
      wordLatin: 'Ror ladu',
      meaning: 'Sweet talks / Flattery',
      category: 'extra',
      order: 343,
    ),
    WordModel(
      id: 'w_extra_144',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱠᱟᱹᱭ',
      wordLatin: 'Mone kay',
      meaning: 'Sin of the heart / Guilty conscience',
      category: 'extra',
      order: 344,
    ),
    WordModel(
      id: 'w_extra_145',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱦᱟᱹᱞᱤ',
      wordLatin: 'Jiwi hali',
      meaning: 'Lively spirit / Fresh energy',
      category: 'extra',
      order: 345,
    ),
    WordModel(
      id: 'w_extra_146',
      wordOlChiki: 'ᱠᱟᱹᱢᱤ ᱞᱟᱹᱜᱤᱫ',
      wordLatin: 'Kami lagid',
      meaning: 'Ready to work',
      category: 'extra',
      order: 346,
    ),
    WordModel(
      id: 'w_extra_147',
      wordOlChiki: 'ᱥᱟᱱᱛᱟᱲᱤ ᱨᱚᱲ',
      wordLatin: 'Santali ror',
      meaning: 'Speaking Santali',
      category: 'extra',
      order: 347,
    ),
    WordModel(
      id: 'w_extra_148',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱩᱭᱦᱟᱹᱨ',
      wordLatin: 'Mone uyhar',
      meaning: 'Thoughts of the heart',
      category: 'extra',
      order: 348,
    ),
    WordModel(
      id: 'w_extra_149',
      wordOlChiki: 'ᱫᱤᱱᱟᱹᱢ ᱫᱟᱠᱟ',
      wordLatin: 'Dinam daka',
      meaning: 'Daily bread',
      category: 'extra',
      order: 349,
    ),
    WordModel(
      id: 'w_extra_150',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱧᱮᱞ',
      wordLatin: 'Sagun njel',
      meaning: 'Good vision / Omen',
      category: 'extra',
      order: 350,
    ),
    WordModel(
      id: 'w_extra_151',
      wordOlChiki: 'ᱦᱚᱲ ᱫᱟᱲᱮ',
      wordLatin: 'Hor dare',
      meaning: 'Collective human strength',
      category: 'extra',
      order: 351,
    ),
    WordModel(
      id: 'w_extra_152',
      wordOlChiki: 'ᱫᱟᱨᱮ ᱜᱮ ᱫᱷᱚᱱ',
      wordLatin: 'Dare ge dhon',
      meaning: 'Forest is wealth',
      category: 'extra',
      order: 352,
    ),
    WordModel(
      id: 'w_extra_153',
      wordOlChiki: 'ᱦᱚᱲ ᱨᱚᱲ ᱵᱩᱨᱩ ᱨᱚᱲ',
      wordLatin: 'Hor ror buru ror',
      meaning: 'Man\'s word is as firm as the hill',
      category: 'extra',
      order: 353,
    ),
    WordModel(
      id: 'w_extra_154',
      wordOlChiki: 'ᱫᱟᱜ ᱨᱮ ᱡᱟᱱᱟᱢ',
      wordLatin: 'Dag re janam',
      meaning: 'Born in water / Pure spirit',
      category: 'extra',
      order: 354,
    ),
    WordModel(
      id: 'w_extra_155',
      wordOlChiki: 'ᱦᱟᱥᱟ ᱦᱚᱲᱢᱚ',
      wordLatin: 'Hasa hormo',
      meaning: 'Clay body / Mortal self',
      category: 'extra',
      order: 355,
    ),
    WordModel(
      id: 'w_extra_156',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ ᱡᱤᱣᱤ',
      wordLatin: 'Sengel jiwi',
      meaning: 'Fiery soul / Passionate spirit',
      category: 'extra',
      order: 356,
    ),
    WordModel(
      id: 'w_extra_157',
      wordOlChiki: 'ᱦᱚᱭ ᱞᱮᱠᱟ ᱫᱟᱹᱲ',
      wordLatin: 'Hoy leka dar',
      meaning: 'Running like the wind / Fleet-footed',
      category: 'extra',
      order: 357,
    ),
    WordModel(
      id: 'w_extra_158',
      wordOlChiki: 'ᱵᱤᱨ ᱩᱢᱩᱞ',
      wordLatin: 'Bir umul',
      meaning: 'Shade of the forest / Nature\'s protection',
      category: 'extra',
      order: 358,
    ),
    WordModel(
      id: 'w_extra_159',
      wordOlChiki: 'ᱫᱟᱨᱮ ᱥᱟᱠᱟᱢ',
      wordLatin: 'Dare sakam',
      meaning: 'Tree leaves / Herbal cure',
      category: 'extra',
      order: 359,
    ),
    WordModel(
      id: 'w_extra_160',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱡᱟᱹᱞᱤ',
      wordLatin: 'Jiwi jhale',
      meaning: 'Snare of life / Interconnected existence',
      category: 'extra',
      order: 360,
    ),
    WordModel(
      id: 'w_extra_161',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱥᱮᱨᱢᱟ',
      wordLatin: 'Sari serma',
      meaning: 'True heavens / Cosmic order',
      category: 'extra',
      order: 361,
    ),
    WordModel(
      id: 'w_extra_162',
      wordOlChiki: 'ᱠᱩᱫᱩᱢ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Kudum katha',
      meaning: 'Riddle talk / Figurative expression',
      category: 'extra',
      order: 362,
    ),
    WordModel(
      id: 'w_extra_163',
      wordOlChiki: 'ᱵᱮᱱᱛᱟ ᱨᱚᱲ',
      wordLatin: 'Benta ror',
      meaning: 'Idiomatic speech / Indirect speech',
      category: 'extra',
      order: 363,
    ),
    WordModel(
      id: 'w_extra_164',
      wordOlChiki: 'ᱦᱟᱲᱟᱢ ᱠᱟᱛᱷᱟ',
      wordLatin: 'Haram katha',
      meaning: 'Ancestral wisdom / Sayings of elders',
      category: 'extra',
      order: 364,
    ),
    WordModel(
      id: 'w_extra_165',
      wordOlChiki: 'ᱵᱩᱰᱷᱤ ᱩᱭᱦᱟᱹᱨ',
      wordLatin: 'Budhi uyhar',
      meaning: 'Wise grandmother\'s advice',
      category: 'extra',
      order: 365,
    ),
    WordModel(
      id: 'w_extra_166',
      wordOlChiki: 'ᱟᱹᱛᱩ ᱟᱹᱨᱤ',
      wordLatin: 'Atu ari',
      meaning: 'Custom of the village',
      category: 'extra',
      order: 366,
    ),
    WordModel(
      id: 'w_extra_167',
      wordOlChiki: 'ᱡᱩᱢᱤᱫᱽ ᱫᱟᱲᱮ',
      wordLatin: 'Jumid dare',
      meaning: 'Strength in unity',
      category: 'extra',
      order: 367,
    ),
    WordModel(
      id: 'w_extra_168',
      wordOlChiki: 'ᱥᱚᱦᱨᱟᱭ ᱥᱮᱨᱮᱧ',
      wordLatin: 'Sohrae serenj',
      meaning: 'Traditional Sohrae harvest songs',
      category: 'extra',
      order: 368,
    ),
    WordModel(
      id: 'w_extra_169',
      wordOlChiki: 'ᱵᱟᱦᱟ ᱥᱟᱠᱟᱢ',
      wordLatin: 'Baha sakam',
      meaning: 'Flower petals / Sacred offerings',
      category: 'extra',
      order: 369,
    ),
    WordModel(
      id: 'w_extra_170',
      wordOlChiki: 'ᱡᱟᱦᱮᱨ ᱩᱢᱩᱞ',
      wordLatin: 'Jaher umul',
      meaning: 'Protection of the sacred grove',
      category: 'extra',
      order: 370,
    ),
    WordModel(
      id: 'w_extra_171',
      wordOlChiki: 'ᱢᱟᱹᱧᱡᱷᱤ ᱵᱤᱪᱟᱹᱨ',
      wordLatin: 'Manjhi bicar',
      meaning: 'Headman\'s judgment / Local justice',
      category: 'extra',
      order: 371,
    ),
    WordModel(
      id: 'w_extra_172',
      wordOlChiki: 'ᱦᱚᱲ ᱫᱷᱚᱨᱚᱢ',
      wordLatin: 'Hor dhorom',
      meaning: 'The way of the Santal / Righteousness',
      category: 'extra',
      order: 372,
    ),
    WordModel(
      id: 'w_extra_173',
      wordOlChiki: 'ᱥᱤᱨᱡᱚᱱ ᱫᱩᱞᱟᱹᱲ',
      wordLatin: 'Sirjon dular',
      meaning: 'Love for nature',
      category: 'extra',
      order: 373,
    ),
    WordModel(
      id: 'w_extra_174',
      wordOlChiki: 'ᱚᱛ ᱦᱟᱥᱟ',
      wordLatin: 'Ot hasa',
      meaning: 'Land and soil / Motherland',
      category: 'extra',
      order: 374,
    ),
    WordModel(
      id: 'w_extra_175',
      wordOlChiki: 'ᱵᱤᱨ ᱡᱟᱱᱣᱟᱨ',
      wordLatin: 'Bir janwar',
      meaning: 'Wild beasts / Forest fauna',
      category: 'extra',
      order: 375,
    ),
    WordModel(
      id: 'w_extra_176',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱥᱟᱠᱟᱢ',
      wordLatin: 'Sagun sakam',
      meaning: 'Auspicious leaf / Sacred message',
      category: 'extra',
      order: 376,
    ),
    WordModel(
      id: 'w_extra_177',
      wordOlChiki: 'ᱢᱟᱹᱱᱢᱤ ᱜᱮᱭᱟᱱ',
      wordLatin: 'Manmi geyan',
      meaning: 'Human wisdom',
      category: 'extra',
      order: 377,
    ),
    WordModel(
      id: 'w_extra_178',
      wordOlChiki: 'ᱜᱚᱡ ᱜᱤᱰᱤ',
      wordLatin: 'Goj gidi',
      meaning: 'Discarded / Dead and thrown / Forgotten',
      category: 'extra',
      order: 378,
    ),
    WordModel(
      id: 'w_extra_179',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱛᱚᱞ',
      wordLatin: 'Jiwi tol',
      meaning: 'Mind bound / Dedication / Vow',
      category: 'extra',
      order: 379,
    ),
    WordModel(
      id: 'w_extra_180',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱛᱷᱟᱹᱭ',
      wordLatin: 'Mone thay',
      meaning: 'Firm decision',
      category: 'extra',
      order: 380,
    ),
    WordModel(
      id: 'w_extra_181',
      wordOlChiki: 'ᱞᱩᱴᱤ ᱡᱚᱢ',
      wordLatin: 'Luti jom',
      meaning: 'Eating through lips / False promises',
      category: 'extra',
      order: 381,
    ),
    WordModel(
      id: 'w_extra_182',
      wordOlChiki: 'ᱢᱩ ᱛᱮ ᱨᱟᱠᱟᱵ',
      wordLatin: 'Mu te rakab',
      meaning: 'Boiling with anger / Nostril rage',
      category: 'extra',
      order: 382,
    ),
    WordModel(
      id: 'w_extra_183',
      wordOlChiki: 'ᱫᱟᱜ ᱫᱷᱤᱨᱤ',
      wordLatin: 'Dag dhiri',
      meaning: 'Wet stone / Indifferent person',
      category: 'extra',
      order: 383,
    ),
    WordModel(
      id: 'w_extra_184',
      wordOlChiki: 'ᱵᱤᱨ ᱫᱟᱨᱮ',
      wordLatin: 'Bir dare',
      meaning: 'Forest trees / Native strength',
      category: 'extra',
      order: 384,
    ),
    WordModel(
      id: 'w_extra_185',
      wordOlChiki: 'ᱦᱟᱥᱟ ᱚᱲᱟᱜ',
      wordLatin: 'Hasa orag',
      meaning: 'Mud house / Humble dwelling',
      category: 'extra',
      order: 385,
    ),
    WordModel(
      id: 'w_extra_186',
      wordOlChiki: 'ᱥᱮᱨᱢᱟ ᱤᱯᱤᱞ',
      wordLatin: 'Serma ipil',
      meaning: 'Heavenly stars / Guide',
      category: 'extra',
      order: 386,
    ),
    WordModel(
      id: 'w_extra_187',
      wordOlChiki: 'ᱧᱤᱫᱟᱹ ᱩᱢᱩᱞ',
      wordLatin: 'Njida umul',
      meaning: 'Night shadow / Mysterious',
      category: 'extra',
      order: 387,
    ),
    WordModel(
      id: 'w_extra_188',
      wordOlChiki: 'ᱥᱤᱸᱜᱮ ᱥᱤᱛᱩᱝ',
      wordLatin: 'Singe situng',
      meaning: 'Scorching midday sun',
      category: 'extra',
      order: 388,
    ),
    WordModel(
      id: 'w_extra_189',
      wordOlChiki: 'ᱨᱤᱢᱤᱞ ᱫᱟᱜ',
      wordLatin: 'Rimil dag',
      meaning: 'Cloud rain / Dynamic blessing',
      category: 'extra',
      order: 389,
    ),
    WordModel(
      id: 'w_extra_190',
      wordOlChiki: 'ᱦᱚᱲ ᱦᱚᱨᱢᱚ',
      wordLatin: 'Hor hormo',
      meaning: 'Santal body / Earthly vessel',
      category: 'extra',
      order: 390,
    ),
    WordModel(
      id: 'w_extra_191',
      wordOlChiki: 'ᱥᱤᱵᱤᱞ ᱥᱟᱹᱜᱟᱹᱭ',
      wordLatin: 'Sibil sagay',
      meaning: 'Sweet relationship / Affectionate bonding',
      category: 'extra',
      order: 391,
    ),
    WordModel(
      id: 'w_extra_192',
      wordOlChiki: 'ᱢᱚᱱᱮ ᱠᱮᱴᱮᱡ',
      wordLatin: 'Mone ketej',
      meaning: 'Strong mind / Brave heart',
      category: 'extra',
      order: 392,
    ),
    WordModel(
      id: 'w_extra_193',
      wordOlChiki: 'ᱡᱤᱣᱤ ᱨᱟᱲᱟ',
      wordLatin: 'Jiwi rara',
      meaning: 'Soul liberation / Ultimate peace',
      category: 'extra',
      order: 393,
    ),
    WordModel(
      id: 'w_extra_194',
      wordOlChiki: 'ᱫᱩᱞᱟᱹᱲ ᱜᱟᱹᱰᱤ',
      wordLatin: 'Dular gadi',
      meaning: 'River of love',
      category: 'extra',
      order: 394,
    ),
    WordModel(
      id: 'w_extra_195',
      wordOlChiki: 'ᱥᱟᱹᱨᱤ ᱜᱩᱨᱩ',
      wordLatin: 'Sari guru',
      meaning: 'True teacher / Master',
      category: 'extra',
      order: 395,
    ),
    WordModel(
      id: 'w_extra_196',
      wordOlChiki: 'ᱜᱮᱭᱟᱱ ᱫᱚᱨᱭᱟ',
      wordLatin: 'Geyan dorya',
      meaning: 'Ocean of knowledge',
      category: 'extra',
      order: 396,
    ),
    WordModel(
      id: 'w_extra_197',
      wordOlChiki: 'ᱞᱟᱠᱪᱟᱨ ᱦᱚᱨ',
      wordLatin: 'Lakchar hor',
      meaning: 'Cultural path',
      category: 'extra',
      order: 397,
    ),
    WordModel(
      id: 'w_extra_198',
      wordOlChiki: 'ᱟᱹᱨᱤ ᱥᱟᱹᱨᱤ',
      wordLatin: 'Ari sari',
      meaning: 'Pure traditions / Absolute truth',
      category: 'extra',
      order: 398,
    ),
    WordModel(
      id: 'w_extra_199',
      wordOlChiki: 'ᱥᱟᱶᱦᱮᱫ ᱡᱤᱣᱤ',
      wordLatin: 'Sawhet jiwi',
      meaning: 'Soul of literature',
      category: 'extra',
      order: 399,
    ),
    WordModel(
      id: 'w_extra_200',
      wordOlChiki: 'ᱥᱤᱨᱡᱚᱱ ᱫᱷᱚᱨᱚᱢ',
      wordLatin: 'Sirjon dhorom',
      meaning: 'Religion of nature',
      category: 'extra',
      order: 400,
    ),
    WordModel(
      id: 'w_extra_201',
      wordOlChiki: 'ᱫᱤᱥᱚᱢ ᱫᱟᱲᱮ',
      wordLatin: 'Disom dare',
      meaning: 'Power of the land',
      category: 'extra',
      order: 401,
    ),
    WordModel(
      id: 'w_extra_202',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱧᱩᱛᱩᱢ',
      wordLatin: 'Sagun nyutum',
      meaning: 'Good name / Renown',
      category: 'extra',
      order: 402,
    ),
    WordModel(
      id: 'w_extra_203',
      wordOlChiki: 'ᱢᱟᱹᱱᱢᱤ ᱫᱷᱚᱨᱚᱢ',
      wordLatin: 'Manmi dhorom',
      meaning: 'Humanity / Service to mankind',
      category: 'extra',
      order: 403,
    ),
    WordModel(
      id: 'w_extra_204',
      wordOlChiki: 'ᱟᱢᱟᱜ ᱧᱩᱛᱩᱢ ᱪᱮᱫ?',
      wordLatin: 'Amag njutum ced?',
      meaning: 'What is your name?',
      category: 'extra',
      order: 404,
    ),
    WordModel(
      id: 'w_extra_205',
      wordOlChiki: 'ᱤᱧᱟᱜ ᱧᱩᱛᱩᱢ ᱫᱚ ... ᱠᱟᱱᱟ',
      wordLatin: 'Injag njutum do ... kana',
      meaning: 'My name is ...',
      category: 'extra',
      order: 405,
    ),
    WordModel(
      id: 'w_extra_206',
      wordOlChiki: 'ᱟᱢ ᱚᱠᱟ ᱠᱷᱚᱱᱮᱢ ᱦᱮᱡ ᱠᱟᱱᱟ?',
      wordLatin: 'Am oka khonem hej kana?',
      meaning: 'Where are you from?',
      category: 'extra',
      order: 406,
    ),
    WordModel(
      id: 'w_extra_207',
      wordOlChiki: 'ᱤᱧ ᱫᱚ ... ᱠᱷᱚᱱᱤᱧ ᱦᱮᱡ ᱠᱟᱱᱟ',
      wordLatin: 'In do ... khoninj hej kana',
      meaning: 'I am from ...',
      category: 'extra',
      order: 407,
    ),
    WordModel(
      id: 'w_extra_208',
      wordOlChiki: 'ᱟᱢ ᱥᱟᱶ ᱧᱟᱯᱟᱢ ᱠᱟᱛᱮ ᱨᱟᱹᱥᱠᱟᱹᱧ ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟ',
      wordLatin: 'Am saw njapam kate raskanj bujhau keda',
      meaning: 'Nice to meet you!',
      category: 'extra',
      order: 408,
    ),
    WordModel(
      id: 'w_extra_209',
      wordOlChiki: 'ᱤᱠᱟᱹ ᱠᱟᱹᱧ ᱢᱮ',
      wordLatin: 'Ika kanj me',
      meaning: 'Excuse me / Sorry',
      category: 'extra',
      order: 409,
    ),
    WordModel(
      id: 'w_extra_210',
      wordOlChiki: 'ᱫᱟᱭᱟ ᱠᱟᱛᱮ',
      wordLatin: 'Daya kate',
      meaning: 'Please',
      category: 'extra',
      order: 410,
    ),
    WordModel(
      id: 'w_extra_211',
      wordOlChiki: 'ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ',
      wordLatin: 'Adi napay',
      meaning: 'Very good / Well done',
      category: 'extra',
      order: 411,
    ),
    WordModel(
      id: 'w_extra_212',
      wordOlChiki: 'ᱜᱟᱯᱟ ᱵᱚᱱ ᱧᱟᱯᱟᱢᱟ',
      wordLatin: 'Gapa bon njapama',
      meaning: 'See you tomorrow',
      category: 'extra',
      order: 412,
    ),
    WordModel(
      id: 'w_extra_213',
      wordOlChiki: 'ᱱᱟᱯᱟᱭ ᱛᱮ ᱛᱟᱦᱮᱸᱱ ᱢᱮ',
      wordLatin: 'Napay te tahen me',
      meaning: 'Take care / Stay well',
      category: 'extra',
      order: 413,
    ),
    WordModel(
      id: 'w_extra_214',
      wordOlChiki: 'ᱤᱧ ᱫᱚᱧ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ',
      wordLatin: 'In donj chalag kana',
      meaning: 'I am leaving now',
      category: 'extra',
      order: 414,
    ),
    WordModel(
      id: 'w_extra_215',
      wordOlChiki: 'ᱫᱩᱞᱟᱹᱲ ᱡᱚᱦᱟᱨ',
      wordLatin: 'Dulaar Johar',
      meaning: 'Goodbye with love',
      category: 'extra',
      order: 415,
    ),
  ];

  Future<void> _loadWords() async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      final data = await db.listDocuments(
        'words',
        queries: [Query.orderAsc('order'), Query.limit(500)],
      );
      state = AsyncValue.data(data.map(WordModel.fromJson).toList());
    } catch (e) {
      state = AsyncValue.data(_seedWords);
    }
  }

  Future<void> add(WordModel item) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.createDocument('words', item.id, item.toJson());
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ add word FAILED: $e');
      rethrow;
    }
  }

  Future<void> update(WordModel item) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.updateDocument('words', item.id, item.toJson());
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ update word FAILED: $e');
      rethrow;
    }
  }

  Future<void> delete(String id) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.deleteDocument('words', id);
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ delete word FAILED: $e');
      rethrow;
    }
  }

  Future<void> addWord(WordModel item) => add(item);
  Future<void> updateWord(WordModel item) => update(item);
  Future<void> deleteWord(String id) => delete(id);

  Future<void> seed() async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      // Fetch all existing documents in the words collection to completely clear legacy records
      final existingDocs = await db.listDocuments('words');
      AppLogger.debug(
        '🧹 Clearing ${existingDocs.length} existing words from database before seeding...',
      );
      for (final doc in existingDocs) {
        final docId = doc['id'] as String;
        try {
          await db.deleteDocument('words', docId);
        } catch (e) {
          AppLogger.debug('⚠️ Failed to delete word document $docId: $e');
        }
      }
    } catch (e) {
      AppLogger.debug('⚠️ Error clearing words collection: $e');
    }

    AppLogger.debug(
      '🌱 Seeding ${_seedWords.length} clean words to database...',
    );
    for (final item in _seedWords) {
      try {
        final db = ref.read(appwriteDbServiceProvider);
        await db.createDocument('words', item.id, item.toJson());
      } catch (e) {
        AppLogger.debug('⚠️ Error seeding word ${item.id}: $e');
      }
    }
    await _loadWords();
  }
}
