import 'package:itun/core/logging/app_logger.dart';
import 'package:appwrite/appwrite.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/api/appwrite_db_service.dart';
import '../models/content_models.dart';

final wordsProvider =
    StateNotifierProvider<WordsNotifier, AsyncValue<List<WordModel>>>(
      WordsNotifier.new,
    );

class WordsNotifier extends StateNotifier<AsyncValue<List<WordModel>>> {
  WordsNotifier(this.ref) : super(const AsyncValue.loading()) {
    _loadWords();
  }

  final Ref ref;

  static final List<WordModel> _seedWords = [
    // ── Greetings & Basics (greeting) ──
    WordModel(
      id: 'w_g1',
      wordOlChiki: 'ᱡᱚᱦᱟᱨ',
      wordLatin: 'Johar',
      meaning: 'Hello / Greetings',
      category: 'greeting',
      order: 1,
    ),
    WordModel(
      id: 'w_g2',
      wordOlChiki: 'ᱥᱟᱨᱦᱟᱣ',
      wordLatin: 'Sarhaw',
      meaning: 'Thank you',
      category: 'greeting',
      order: 2,
    ),
    WordModel(
      id: 'w_g3',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
      wordLatin: 'Sagun Daram',
      meaning: 'Welcome',
      category: 'greeting',
      order: 3,
    ),
    WordModel(
      id: 'w_g4',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱥᱮᱛᱟᱜ',
      wordLatin: 'Sagun Setag',
      meaning: 'Good morning',
      category: 'greeting',
      order: 4,
    ),
    WordModel(
      id: 'w_g5',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱧᱤᱫᱟᱹ',
      wordLatin: 'Sagun Njida',
      meaning: 'Good night',
      category: 'greeting',
      order: 5,
    ),
    WordModel(
      id: 'w_g6',
      wordOlChiki: 'ᱡᱚᱦᱟᱨ ᱜᱮ',
      wordLatin: 'Johar ge',
      meaning: 'Greetings to you',
      category: 'greeting',
      order: 6,
    ),
    WordModel(
      id: 'w_g7',
      wordOlChiki: 'ᱱᱟᱯᱟᱭ ᱜᱮ',
      wordLatin: 'Napay ge',
      meaning: 'Just fine',
      category: 'greeting',
      order: 7,
    ),
    WordModel(
      id: 'w_g8',
      wordOlChiki: 'ᱢᱟᱨᱟᱝ ᱡᱚᱦᱟᱨ',
      wordLatin: 'Marang Johar',
      meaning: 'Great respect hello',
      category: 'greeting',
      order: 8,
    ),
    WordModel(
      id: 'w_g9',
      wordOlChiki: 'ᱜᱩᱱ ᱢᱟᱱᱟᱣ',
      wordLatin: 'Gun Manaw',
      meaning: 'Respect / Honor',
      category: 'greeting',
      order: 9,
    ),
    WordModel(
      id: 'w_g10',
      wordOlChiki: 'ᱡᱤᱭᱟᱹᱲ',
      wordLatin: 'Jiyar',
      meaning: 'Long live / Live well',
      category: 'greeting',
      order: 10,
    ),
    WordModel(
      id: 'w_g11',
      wordOlChiki: 'ᱞᱟᱥᱟᱬᱦᱮᱫ',
      wordLatin: 'Lasanhed',
      meaning: 'Sweet greetings',
      category: 'greeting',
      order: 11,
    ),
    WordModel(
      id: 'w_g12',
      wordOlChiki: 'ᱦᱮᱞᱢᱮᱞ',
      wordLatin: 'Helmel',
      meaning: 'Friendly association',
      category: 'greeting',
      order: 12,
    ),
    WordModel(
      id: 'w_g13',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱛᱤᱠᱤᱱ',
      wordLatin: 'Sagun Tikin',
      meaning: 'Good afternoon',
      category: 'greeting',
      order: 13,
    ),
    WordModel(
      id: 'w_g14',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱟᱹᱭᱩᱵ',
      wordLatin: 'Sagun Ayub',
      meaning: 'Good evening',
      category: 'greeting',
      order: 14,
    ),
    WordModel(
      id: 'w_g15',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱥᱤᱸᱜᱮ',
      wordLatin: 'Sagun Singe',
      meaning: 'Blessed Sunday',
      category: 'greeting',
      order: 15,
    ),
    WordModel(
      id: 'w_g16',
      wordOlChiki: 'ᱥᱟᱹᱜᱩᱱ ᱫᱤᱱ',
      wordLatin: 'Sagun Din',
      meaning: 'Good day',
      category: 'greeting',
      order: 16,
    ),
    WordModel(
      id: 'w_g17',
      wordOlChiki: 'ᱢᱟ ᱡᱚᱦᱟᱨ',
      wordLatin: 'Ma Johar',
      meaning: 'Formal goodbye / respect',
      category: 'greeting',
      order: 17,
    ),
    WordModel(
      id: 'w_g18',
      wordOlChiki: 'ᱛᱟᱦᱮᱸᱱ',
      wordLatin: 'Tahen',
      meaning: 'Goodbye (stay well)',
      category: 'greeting',
      order: 18,
    ),
    WordModel(
      id: 'w_g19',
      wordOlChiki: 'ᱥᱮᱱᱚᱜ',
      wordLatin: 'Senog',
      meaning: 'Goodbye (go well)',
      category: 'greeting',
      order: 19,
    ),
    WordModel(
      id: 'w_g20',
      wordOlChiki: 'ᱥᱟᱨᱦᱟᱣ ᱜᱮ',
      wordLatin: 'Sarhaw ge',
      meaning: 'Thank you indeed',
      category: 'greeting',
      order: 20,
    ),

    // ── Basics (basic) ──
    WordModel(
      id: 'w_b1',
      wordOlChiki: 'ᱦᱮᱸ',
      wordLatin: 'Hẽ',
      meaning: 'Yes',
      category: 'basic',
      order: 21,
    ),
    WordModel(
      id: 'w_b2',
      wordOlChiki: 'ᱵᱟᱝ',
      wordLatin: 'Bang',
      meaning: 'No',
      category: 'basic',
      order: 22,
    ),
    WordModel(
      id: 'w_b3',
      wordOlChiki: 'ᱪᱮᱫ',
      wordLatin: 'Ced',
      meaning: 'What',
      category: 'basic',
      order: 23,
    ),
    WordModel(
      id: 'w_b4',
      wordOlChiki: 'ᱚᱠᱚᱭ',
      wordLatin: 'Okoy',
      meaning: 'Who',
      category: 'basic',
      order: 24,
    ),
    WordModel(
      id: 'w_b5',
      wordOlChiki: 'ᱚᱠᱟ',
      wordLatin: 'Oka',
      meaning: 'Which',
      category: 'basic',
      order: 25,
    ),
    WordModel(
      id: 'w_b6',
      wordOlChiki: 'ᱪᱮᱞᱮᱠᱟ',
      wordLatin: 'Celeka',
      meaning: 'How',
      category: 'basic',
      order: 26,
    ),
    WordModel(
      id: 'w_b7',
      wordOlChiki: 'ᱛᱤᱥ',
      wordLatin: 'Tis',
      meaning: 'When',
      category: 'basic',
      order: 27,
    ),
    WordModel(
      id: 'w_b8',
      wordOlChiki: 'ᱚᱠᱟᱨᱮ',
      wordLatin: 'Okare',
      meaning: 'Where',
      category: 'basic',
      order: 28,
    ),
    WordModel(
      id: 'w_b9',
      wordOlChiki: 'ᱤᱧ',
      wordLatin: 'Inj',
      meaning: 'I / Me',
      category: 'basic',
      order: 29,
    ),
    WordModel(
      id: 'w_b10',
      wordOlChiki: 'ᱟᱢ',
      wordLatin: 'Am',
      meaning: 'You',
      category: 'basic',
      order: 30,
    ),
    WordModel(
      id: 'w_b11',
      wordOlChiki: 'ᱩᱱᱤ',
      wordLatin: 'Uni',
      meaning: 'He / She',
      category: 'basic',
      order: 31,
    ),
    WordModel(
      id: 'w_b12',
      wordOlChiki: 'ᱱᱩᱭ',
      wordLatin: 'Nuy',
      meaning: 'This person',
      category: 'basic',
      order: 32,
    ),
    WordModel(
      id: 'w_b13',
      wordOlChiki: 'ᱦᱟᱹᱱᱤ',
      wordLatin: 'Hani',
      meaning: 'That person (far)',
      category: 'basic',
      order: 33,
    ),
    WordModel(
      id: 'w_b14',
      wordOlChiki: 'ᱚᱱᱟ',
      wordLatin: 'Ona',
      meaning: 'That thing',
      category: 'basic',
      order: 34,
    ),
    WordModel(
      id: 'w_b15',
      wordOlChiki: 'ᱱᱚᱶᱟ',
      wordLatin: 'Nowa',
      meaning: 'This thing',
      category: 'basic',
      order: 35,
    ),
    WordModel(
      id: 'w_b16',
      wordOlChiki: 'ᱟᱹᱰᱤ',
      wordLatin: 'Adi',
      meaning: 'Very',
      category: 'basic',
      order: 36,
    ),
    WordModel(
      id: 'w_b17',
      wordOlChiki: 'ᱠᱟᱹᱡ',
      wordLatin: 'Kaj',
      meaning: 'Few / A little',
      category: 'basic',
      order: 37,
    ),
    WordModel(
      id: 'w_b18',
      wordOlChiki: 'ᱡᱷᱚᱛᱚ',
      wordLatin: 'Jhoto',
      meaning: 'All',
      category: 'basic',
      order: 38,
    ),
    WordModel(
      id: 'w_b19',
      wordOlChiki: 'ᱪᱤᱞᱤ',
      wordLatin: 'Cili',
      meaning: 'What kind of living being',
      category: 'basic',
      order: 39,
    ),
    WordModel(
      id: 'w_b20',
      wordOlChiki: 'ᱱᱟᱥᱮ',
      wordLatin: 'Nase',
      meaning: 'Slightly',
      category: 'basic',
      order: 40,
    ),

    // ── Family & Relationships (family) ──
    WordModel(
      id: 'w_f1',
      wordOlChiki: 'ᱵᱟᱵᱟ',
      wordLatin: 'Baba',
      meaning: 'Father',
      category: 'family',
      order: 41,
    ),
    WordModel(
      id: 'w_f2',
      wordOlChiki: 'ᱟᱭᱳ',
      wordLatin: 'Ayo',
      meaning: 'Mother',
      category: 'family',
      order: 42,
    ),
    WordModel(
      id: 'w_f3',
      wordOlChiki: 'ᱳᱲᱟᱜ ᱦᱚᱲ',
      wordLatin: 'Orag hor',
      meaning: 'Spouse / Family member',
      category: 'family',
      order: 43,
    ),
    WordModel(
      id: 'w_f4',
      wordOlChiki: 'ᱫᱟᱫᱟ',
      wordLatin: 'Dada',
      meaning: 'Elder brother',
      category: 'family',
      order: 44,
    ),
    WordModel(
      id: 'w_f5',
      wordOlChiki: 'ᱫᱟᱹᱭ',
      wordLatin: 'Dai',
      meaning: 'Elder sister',
      category: 'family',
      order: 45,
    ),
    WordModel(
      id: 'w_f6',
      wordOlChiki: 'ᱵᱚᱠᱚᱧ',
      wordLatin: 'Bokonj',
      meaning: 'Younger brother',
      category: 'family',
      order: 46,
    ),
    WordModel(
      id: 'w_f7',
      wordOlChiki: 'ᱢᱤᱥᱮᱨᱟ',
      wordLatin: 'Misera',
      meaning: 'Younger sister',
      category: 'family',
      order: 47,
    ),
    WordModel(
      id: 'w_f8',
      wordOlChiki: 'ᱦᱚᱯᱚᱱ',
      wordLatin: 'Hopon',
      meaning: 'Son / Child',
      category: 'family',
      order: 48,
    ),
    WordModel(
      id: 'w_f9',
      wordOlChiki: 'ᱦᱚᱯᱚᱱ ᱮᱨᱟ',
      wordLatin: 'Hopon era',
      meaning: 'Daughter',
      category: 'family',
      order: 49,
    ),
    WordModel(
      id: 'w_f10',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ ᱵᱟᱵᱟ',
      wordLatin: 'Gorom baba',
      meaning: 'Grandfather',
      category: 'family',
      order: 50,
    ),
    WordModel(
      id: 'w_f11',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ ᱟᱭᱳ',
      wordLatin: 'Gorom ayo',
      meaning: 'Grandmother',
      category: 'family',
      order: 51,
    ),
    WordModel(
      id: 'w_f12',
      wordOlChiki: 'ᱠᱟᱠᱟ',
      wordLatin: 'Kaka',
      meaning: 'Uncle (father\'s younger brother)',
      category: 'family',
      order: 52,
    ),
    WordModel(
      id: 'w_f13',
      wordOlChiki: 'ᱠᱟᱠᱤ',
      wordLatin: 'Kaki',
      meaning: 'Aunt (father\'s younger brother\'s wife)',
      category: 'family',
      order: 53,
    ),
    WordModel(
      id: 'w_f14',
      wordOlChiki: 'ᱢᱟᱢᱚ',
      wordLatin: 'Mamo',
      meaning: 'Maternal uncle',
      category: 'family',
      order: 54,
    ),
    WordModel(
      id: 'w_f15',
      wordOlChiki: 'ᱦᱟᱛᱚᱢ',
      wordLatin: 'Hatom',
      meaning: 'Paternal aunt',
      category: 'family',
      order: 55,
    ),
    WordModel(
      id: 'w_f16',
      wordOlChiki: 'ᱛᱮᱧᱟᱝ',
      wordLatin: 'Tenjang',
      meaning: 'Brother-in-law (sister\'s husband)',
      category: 'family',
      order: 56,
    ),
    WordModel(
      id: 'w_f17',
      wordOlChiki: 'ᱦᱤᱞᱤ',
      wordLatin: 'Hili',
      meaning: 'Sister-in-law (brother\'s wife)',
      category: 'family',
      order: 57,
    ),
    WordModel(
      id: 'w_f18',
      wordOlChiki: 'ᱵᱟᱹᱦᱩ',
      wordLatin: 'Bahu',
      meaning: 'Wife / Bride',
      category: 'family',
      order: 58,
    ),
    WordModel(
      id: 'w_f19',
      wordOlChiki: 'ᱡᱟᱶᱟᱭ',
      wordLatin: 'Jaway',
      meaning: 'Husband / Groom',
      category: 'family',
      order: 59,
    ),
    WordModel(
      id: 'w_f20',
      wordOlChiki: 'ᱜᱚᱲᱚᱢ',
      wordLatin: 'Gorom',
      meaning: 'Grandchild',
      category: 'family',
      order: 60,
    ),

    // ── Daily Use Words (daily) ──
    WordModel(
      id: 'w_d1',
      wordOlChiki: 'ᱫᱟᱜ',
      wordLatin: 'Dag',
      meaning: 'Water',
      category: 'daily',
      order: 61,
    ),
    WordModel(
      id: 'w_d2',
      wordOlChiki: 'ᱫᱟᱠᱟ',
      wordLatin: 'Daka',
      meaning: 'Cooked Rice / Food',
      category: 'daily',
      order: 62,
    ),
    WordModel(
      id: 'w_d3',
      wordOlChiki: 'ᱳᱲᱟᱜ',
      wordLatin: 'Orag',
      meaning: 'Home / House',
      category: 'daily',
      order: 63,
    ),
    WordModel(
      id: 'w_d4',
      wordOlChiki: 'ᱠᱤᱪᱨᱤᱡ',
      wordLatin: 'Kicrij',
      meaning: 'Cloth',
      category: 'daily',
      order: 64,
    ),
    WordModel(
      id: 'w_d5',
      wordOlChiki: 'ᱦᱚᱨ',
      wordLatin: 'Hor',
      meaning: 'Path / Road',
      category: 'daily',
      order: 65,
    ),
    WordModel(
      id: 'w_d6',
      wordOlChiki: 'ᱟᱹᱛᱩ',
      wordLatin: 'Atu',
      meaning: 'Village',
      category: 'daily',
      order: 66,
    ),
    WordModel(
      id: 'w_d7',
      wordOlChiki: 'ᱴᱟᱠᱟ',
      wordLatin: 'Taka',
      meaning: 'Money',
      category: 'daily',
      order: 67,
    ),
    WordModel(
      id: 'w_d8',
      wordOlChiki: 'ᱠᱟᱹᱢᱤ',
      wordLatin: 'Kami',
      meaning: 'Work / Job',
      category: 'daily',
      order: 68,
    ),
    WordModel(
      id: 'w_d9',
      wordOlChiki: 'ᱡᱟᱹᱯᱤᱫ',
      wordLatin: 'Japid',
      meaning: 'Sleep',
      category: 'daily',
      order: 69,
    ),
    WordModel(
      id: 'w_d10',
      wordOlChiki: 'ᱛᱩᱯᱩᱱ',
      wordLatin: 'Tupun',
      meaning: 'Bathing',
      category: 'daily',
      order: 70,
    ),
    WordModel(
      id: 'w_d11',
      wordOlChiki: 'ᱥᱮᱱᱚᱜ',
      wordLatin: 'Senog',
      meaning: 'Going',
      category: 'daily',
      order: 71,
    ),
    WordModel(
      id: 'w_d12',
      wordOlChiki: 'ᱦᱤᱡᱩᱜ',
      wordLatin: 'Hijug',
      meaning: 'Coming',
      category: 'daily',
      order: 72,
    ),
    WordModel(
      id: 'w_d13',
      wordOlChiki: 'ᱫᱩᱲᱩᱵ',
      wordLatin: 'Durub',
      meaning: 'Sit',
      category: 'daily',
      order: 73,
    ),
    WordModel(
      id: 'w_d14',
      wordOlChiki: 'ᱛᱮᱸᱜᱚ',
      wordLatin: 'Tengo',
      meaning: 'Stand',
      category: 'daily',
      order: 74,
    ),
    WordModel(
      id: 'w_d15',
      wordOlChiki: 'ᱫᱟᱹᱲ',
      wordLatin: 'Dar',
      meaning: 'Run',
      category: 'daily',
      order: 75,
    ),
    WordModel(
      id: 'w_d16',
      wordOlChiki: 'ᱛᱟᱲᱟᱢ',
      wordLatin: 'Taram',
      meaning: 'Walk',
      category: 'daily',
      order: 76,
    ),
    WordModel(
      id: 'w_d17',
      wordOlChiki: 'ᱨᱚᱲ',
      wordLatin: 'Ror',
      meaning: 'Speak / Talk',
      category: 'daily',
      order: 77,
    ),
    WordModel(
      id: 'w_d18',
      wordOlChiki: 'ᱟᱸᱡᱚᱢ',
      wordLatin: 'Anjom',
      meaning: 'Hear / Listen',
      category: 'daily',
      order: 78,
    ),
    WordModel(
      id: 'w_d19',
      wordOlChiki: 'ᱧᱮᱞ',
      wordLatin: 'Njel',
      meaning: 'See / Look',
      category: 'daily',
      order: 79,
    ),
    WordModel(
      id: 'w_d20',
      wordOlChiki: 'ᱚᱞ',
      wordLatin: 'Ol',
      meaning: 'Write',
      category: 'daily',
      order: 80,
    ),

    // ── Colors (colors) ──
    WordModel(
      id: 'w_c1',
      wordOlChiki: 'ᱟᱨᱟᱜ',
      wordLatin: 'Arag',
      meaning: 'Red',
      category: 'colors',
      order: 81,
      themeColor: '#EF4444',
    ),
    WordModel(
      id: 'w_c2',
      wordOlChiki: 'ᱥᱟᱥᱟᱝ',
      wordLatin: 'Sasang',
      meaning: 'Yellow',
      category: 'colors',
      order: 82,
      themeColor: '#EAB308',
    ),
    WordModel(
      id: 'w_c3',
      wordOlChiki: 'ᱦᱟᱹᱨᱭᱟᱹᱲ',
      wordLatin: 'Haryar',
      meaning: 'Green',
      category: 'colors',
      order: 83,
      themeColor: '#10B981',
    ),
    WordModel(
      id: 'w_c4',
      wordOlChiki: 'ᱯᱩᱸᱰ',
      wordLatin: 'Pund',
      meaning: 'White',
      category: 'colors',
      order: 84,
      themeColor: '#FFFFFF',
    ),
    WordModel(
      id: 'w_c5',
      wordOlChiki: 'ᱦᱮᱱᱫᱮ',
      wordLatin: 'Hende',
      meaning: 'Black',
      category: 'colors',
      order: 85,
      themeColor: '#1E293B',
    ),
    WordModel(
      id: 'w_c6',
      wordOlChiki: 'ᱞᱤᱞ',
      wordLatin: 'Lil',
      meaning: 'Blue',
      category: 'colors',
      order: 86,
      themeColor: '#3B82F6',
    ),
    WordModel(
      id: 'w_c7',
      wordOlChiki: 'ᱜᱩᱞᱟᱹᱯᱤ',
      wordLatin: 'Gulapi',
      meaning: 'Pink',
      category: 'colors',
      order: 87,
      themeColor: '#F43F5E',
    ),
    WordModel(
      id: 'w_c8',
      wordOlChiki: 'ᱠᱷᱟᱹᱠᱨᱤ',
      wordLatin: 'Khakri',
      meaning: 'Brown',
      category: 'colors',
      order: 88,
      themeColor: '#78350F',
    ),
    WordModel(
      id: 'w_c9',
      wordOlChiki: 'ᱠᱟᱹᱦᱞᱟᱹ',
      wordLatin: 'Kahla',
      meaning: 'Purple / Violet',
      category: 'colors',
      order: 89,
      themeColor: '#475569', // Avoid violet/purple per ban
    ),
    WordModel(
      id: 'w_c10',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ ᱟᱨᱟᱜ',
      wordLatin: 'Sengel arag',
      meaning: 'Fiery Red',
      category: 'colors',
      order: 90,
      themeColor: '#DC2626',
    ),
    WordModel(
      id: 'w_c11',
      wordOlChiki: 'ᱢᱮᱫ ᱟᱨᱟᱜ',
      wordLatin: 'Med arag',
      meaning: 'Crimson',
      category: 'colors',
      order: 91,
      themeColor: '#991B1B',
    ),
    WordModel(
      id: 'w_c12',
      wordOlChiki: 'ᱦᱟᱥᱟ',
      wordLatin: 'Hasa',
      meaning: 'Clay-colored / Earthy grey',
      category: 'colors',
      order: 92,
      themeColor: '#78716C',
    ),
    WordModel(
      id: 'w_c13',
      wordOlChiki: 'ᱥᱚᱱᱟ',
      wordLatin: 'Sona',
      meaning: 'Golden',
      category: 'colors',
      order: 93,
      themeColor: '#D97706',
    ),
    WordModel(
      id: 'w_c14',
      wordOlChiki: 'ᱨᱩᱯᱟᱹ',
      wordLatin: 'Rupa',
      meaning: 'Silvery',
      category: 'colors',
      order: 94,
      themeColor: '#CBD5E1',
    ),
    WordModel(
      id: 'w_c15',
      wordOlChiki: 'ᱞᱟᱹᱰᱩ',
      wordLatin: 'Ladu orange',
      meaning: 'Orange',
      category: 'colors',
      order: 95,
      themeColor: '#F97316',
    ),
    WordModel(
      id: 'w_c16',
      wordOlChiki: 'ᱪᱩᱱ',
      wordLatin: 'Cun',
      meaning: 'Lime white',
      category: 'colors',
      order: 96,
      themeColor: '#F8FAFC',
    ),
    WordModel(
      id: 'w_c17',
      wordOlChiki: 'ᱠᱩᱭᱞᱟᱹ',
      wordLatin: 'Kuyla',
      meaning: 'Coal black',
      category: 'colors',
      order: 97,
      themeColor: '#0F172A',
    ),
    WordModel(
      id: 'w_c18',
      wordOlChiki: 'ᱞᱤᱞᱪᱷᱟᱴᱟ',
      wordLatin: 'Lilchata',
      meaning: 'Light blue',
      category: 'colors',
      order: 98,
      themeColor: '#7DD3FC',
    ),
    WordModel(
      id: 'w_c19',
      wordOlChiki: 'ᱡᱟᱹᱨᱫᱤ',
      wordLatin: 'Jardi',
      meaning: 'Deep yellow',
      category: 'colors',
      order: 99,
      themeColor: '#EAB308',
    ),
    WordModel(
      id: 'w_c20',
      wordOlChiki: 'ᱦᱟᱹᱨᱭᱟᱹᱲᱪᱷᱟᱴᱟ',
      wordLatin: 'Haryarchata',
      meaning: 'Pale green',
      category: 'colors',
      order: 100,
      themeColor: '#86EFAC',
    ),

    // ── Animals & Nature (nature) ──
    WordModel(
      id: 'w_n1',
      wordOlChiki: 'ᱥᱮᱛᱟ',
      wordLatin: 'Seta',
      meaning: 'Dog',
      category: 'nature',
      order: 101,
    ),
    WordModel(
      id: 'w_n2',
      wordOlChiki: 'ᱯᱩᱥᱤ',
      wordLatin: 'Pusi',
      meaning: 'Cat',
      category: 'nature',
      order: 102,
    ),
    WordModel(
      id: 'w_n3',
      wordOlChiki: 'ᱢᱮᱨᱳᱢ',
      wordLatin: 'Merom',
      meaning: 'Goat',
      category: 'nature',
      order: 103,
    ),
    WordModel(
      id: 'w_n4',
      wordOlChiki: 'ᱜᱟᱹᱭ',
      wordLatin: 'Gai',
      meaning: 'Cow',
      category: 'nature',
      order: 104,
    ),
    WordModel(
      id: 'w_n5',
      wordOlChiki: 'ᱛᱟᱹᱨᱩᱵ',
      wordLatin: 'Tarub',
      meaning: 'Tiger',
      category: 'nature',
      order: 105,
    ),
    WordModel(
      id: 'w_n6',
      wordOlChiki: 'ᱪᱮᱬᱮ',
      wordLatin: 'Cene',
      meaning: 'Bird',
      category: 'nature',
      order: 106,
    ),
    WordModel(
      id: 'w_n7',
      wordOlChiki: 'ᱦᱟᱹᱠᱩ',
      wordLatin: 'Haku',
      meaning: 'Fish',
      category: 'nature',
      order: 107,
    ),
    WordModel(
      id: 'w_n8',
      wordOlChiki: 'ᱫᱟᱨᱮ',
      wordLatin: 'Dare',
      meaning: 'Tree',
      category: 'nature',
      order: 108,
    ),
    WordModel(
      id: 'w_n9',
      wordOlChiki: 'ᱵᱟᱦᱟ',
      wordLatin: 'Baha',
      meaning: 'Flower',
      category: 'nature',
      order: 109,
    ),
    WordModel(
      id: 'w_n10',
      wordOlChiki: 'ᱥᱤᱧ',
      wordLatin: 'Sing',
      meaning: 'Sun',
      category: 'nature',
      order: 110,
    ),
    WordModel(
      id: 'w_n11',
      wordOlChiki: 'ᱤᱯᱤᱞ',
      wordLatin: 'Ipil',
      meaning: 'Star',
      category: 'nature',
      order: 111,
    ),
    WordModel(
      id: 'w_n12',
      wordOlChiki: 'ᱠᱟᱰᱟ',
      wordLatin: 'Kada',
      meaning: 'Buffalo',
      category: 'nature',
      order: 112,
    ),
    WordModel(
      id: 'w_n13',
      wordOlChiki: 'ᱥᱟᱫᱚᱢ',
      wordLatin: 'Sadom',
      meaning: 'Horse',
      category: 'nature',
      order: 113,
    ),
    WordModel(
      id: 'w_n14',
      wordOlChiki: 'ᱦᱟᱹᱛᱤ',
      wordLatin: 'Hati',
      meaning: 'Elephant',
      category: 'nature',
      order: 114,
    ),
    WordModel(
      id: 'w_n15',
      wordOlChiki: 'ᱵᱤᱧ',
      wordLatin: 'Binj',
      meaning: 'Snake',
      category: 'nature',
      order: 115,
    ),
    WordModel(
      id: 'w_n16',
      wordOlChiki: 'ᱥᱟᱠᱟᱢ',
      wordLatin: 'Sakam',
      meaning: 'Leaf',
      category: 'nature',
      order: 116,
    ),
    WordModel(
      id: 'w_n17',
      wordOlChiki: 'ᱨᱤᱢᱤᱞ',
      wordLatin: 'Rimil',
      meaning: 'Cloud',
      category: 'nature',
      order: 117,
    ),
    WordModel(
      id: 'w_n18',
      wordOlChiki: 'ᱥᱮᱸᱜᱮᱞ',
      wordLatin: 'Sengel',
      meaning: 'Fire',
      category: 'nature',
      order: 118,
    ),
    WordModel(
      id: 'w_n19',
      wordOlChiki: 'ᱦᱚᱭ',
      wordLatin: 'Hoy',
      meaning: 'Wind / Air',
      category: 'nature',
      order: 119,
    ),
    WordModel(
      id: 'w_n20',
      wordOlChiki: 'ᱦᱟᱥᱟ',
      wordLatin: 'Hasa',
      meaning: 'Soil / Earth',
      category: 'nature',
      order: 120,
    ),

    // ── Months, Days & Seasons (time) ──
    WordModel(
      id: 'w_t1',
      wordOlChiki: 'ᱪᱟᱸᱫᱚ',
      wordLatin: 'Chando',
      meaning: 'Month / Moon',
      category: 'time',
      order: 121,
    ),
    WordModel(
      id: 'w_t2',
      wordOlChiki: 'ᱢᱟᱦᱟ',
      wordLatin: 'Maha',
      meaning: 'Day',
      category: 'time',
      order: 122,
    ),
    WordModel(
      id: 'w_t3',
      wordOlChiki: 'ᱛᱮᱦᱮᱧ',
      wordLatin: 'Tehenj',
      meaning: 'Today',
      category: 'time',
      order: 123,
    ),
    WordModel(
      id: 'w_t4',
      wordOlChiki: 'ᱜᱟᱯᱟ',
      wordLatin: 'Gapa',
      meaning: 'Tomorrow',
      category: 'time',
      order: 124,
    ),
    WordModel(
      id: 'w_t5',
      wordOlChiki: 'ᱦᱚᱞᱟ',
      wordLatin: 'Hola',
      meaning: 'Yesterday',
      category: 'time',
      order: 125,
    ),
    WordModel(
      id: 'w_t6',
      wordOlChiki: 'ᱥᱤᱛᱩᱝ ᱨᱤᱛᱩ',
      wordLatin: 'Situng ritu',
      meaning: 'Summer',
      category: 'time',
      order: 126,
    ),
    WordModel(
      id: 'w_t7',
      wordOlChiki: 'ᱫᱟᱜ ᱨᱤᱛᱩ',
      wordLatin: 'Dag ritu',
      meaning: 'Rainy Season',
      category: 'time',
      order: 127,
    ),
    WordModel(
      id: 'w_t8',
      wordOlChiki: 'ᱨᱟᱵᱟᱝ ᱨᱤᱛᱩ',
      wordLatin: 'Rabang ritu',
      meaning: 'Winter',
      category: 'time',
      order: 128,
    ),
    WordModel(
      id: 'w_t9',
      wordOlChiki: 'ᱥᱮᱨᱢᱟ',
      wordLatin: 'Serma',
      meaning: 'Year',
      category: 'time',
      order: 129,
    ),
    WordModel(
      id: 'w_t10',
      wordOlChiki: 'ᱦᱟᱯᱛᱟ',
      wordLatin: 'Hapta',
      meaning: 'Week',
      category: 'time',
      order: 130,
    ),
    WordModel(
      id: 'w_t11',
      wordOlChiki: 'ᱜᱷᱟᱱᱴᱟ',
      wordLatin: 'Ghanta',
      meaning: 'Hour',
      category: 'time',
      order: 131,
    ),
    WordModel(
      id: 'w_t12',
      wordOlChiki: 'ᱴᱤᱲᱤᱡ',
      wordLatin: 'Tirij',
      meaning: 'Minute',
      category: 'time',
      order: 132,
    ),
    WordModel(
      id: 'w_t13',
      wordOlChiki: 'ᱥᱮᱛᱟᱜ',
      wordLatin: 'Setag',
      meaning: 'Morning',
      category: 'time',
      order: 133,
    ),
    WordModel(
      id: 'w_t14',
      wordOlChiki: 'ᱛᱤᱠᱤᱱ',
      wordLatin: 'Tikin',
      meaning: 'Noon',
      category: 'time',
      order: 134,
    ),
    WordModel(
      id: 'w_t15',
      wordOlChiki: 'ᱟᱹᱭᱩᱵ',
      wordLatin: 'Ayub',
      meaning: 'Evening',
      category: 'time',
      order: 135,
    ),
    WordModel(
      id: 'w_t16',
      wordOlChiki: 'ᱧᱤᱫᱟᱹ',
      wordLatin: 'Njida',
      meaning: 'Night',
      category: 'time',
      order: 136,
    ),
    WordModel(
      id: 'w_t17',
      wordOlChiki: 'ᱢᱮᱭᱟᱝ',
      wordLatin: 'Meyang',
      meaning: 'Day after tomorrow',
      category: 'time',
      order: 137,
    ),
    WordModel(
      id: 'w_t18',
      wordOlChiki: 'ᱢᱟᱦᱟᱸᱫᱮᱨ',
      wordLatin: 'Mahander',
      meaning: 'Day before yesterday',
      category: 'time',
      order: 138,
    ),
    WordModel(
      id: 'w_t19',
      wordOlChiki: 'ᱱᱤᱛᱚᱜ',
      wordLatin: 'Nitog',
      meaning: 'Now',
      category: 'time',
      order: 139,
    ),
    WordModel(
      id: 'w_t20',
      wordOlChiki: 'ᱛᱟᱭᱚᱢ',
      wordLatin: 'Tayom',
      meaning: 'Later',
      category: 'time',
      order: 140,
    ),

    // ── Trending & Popular (trending) ──
    WordModel(
      id: 'w_tr1',
      wordOlChiki: 'ᱯᱟᱹᱨᱥᱤ',
      wordLatin: 'Parsi',
      meaning: 'Language',
      category: 'trending',
      order: 141,
    ),
    WordModel(
      id: 'w_tr2',
      wordOlChiki: 'ᱥᱟᱱᱛᱟᱲᱤ',
      wordLatin: 'Santali',
      meaning: 'Santali',
      category: 'trending',
      order: 142,
    ),
    WordModel(
      id: 'w_tr3',
      wordOlChiki: 'ᱚᱞ ᱪᱤᱠᱤ',
      wordLatin: 'Ol Chiki',
      meaning: 'Ol Chiki Script',
      category: 'trending',
      order: 143,
    ),
    WordModel(
      id: 'w_tr4',
      wordOlChiki: 'ᱯᱩᱛᱷᱤ',
      wordLatin: 'Puthi',
      meaning: 'Book',
      category: 'trending',
      order: 144,
    ),
    WordModel(
      id: 'w_tr5',
      wordOlChiki: 'ᱤᱛᱩᱱ ᱟᱥᱲᱟ',
      wordLatin: 'Itun asra',
      meaning: 'School',
      category: 'trending',
      order: 145,
    ),
    WordModel(
      id: 'w_tr6',
      wordOlChiki: 'ᱫᱤᱥᱚᱢ',
      wordLatin: 'Disom',
      meaning: 'Country',
      category: 'trending',
      order: 146,
    ),
    WordModel(
      id: 'w_tr7',
      wordOlChiki: 'ᱦᱚᱲ',
      wordLatin: 'Hor',
      meaning: 'People',
      category: 'trending',
      order: 147,
    ),
    WordModel(
      id: 'w_tr8',
      wordOlChiki: 'ᱥᱮᱨᱮᱧ',
      wordLatin: 'Serenj',
      meaning: 'Song / Sing',
      category: 'trending',
      order: 148,
    ),
    WordModel(
      id: 'w_tr9',
      wordOlChiki: 'ᱮᱱᱮᱡ',
      wordLatin: 'Enej',
      meaning: 'Dance',
      category: 'trending',
      order: 149,
    ),
    WordModel(
      id: 'w_tr10',
      wordOlChiki: 'ᱯᱚᱨᱚᱵ',
      wordLatin: 'Porob',
      meaning: 'Festival',
      category: 'trending',
      order: 150,
    ),
    WordModel(
      id: 'w_tr11',
      wordOlChiki: 'ᱥᱚᱦᱨᱟᱭ',
      wordLatin: 'Sohrae',
      meaning: 'Sohrae Festival',
      category: 'trending',
      order: 151,
    ),
    WordModel(
      id: 'w_tr12',
      wordOlChiki: 'ᱵᱟᱦᱟ',
      wordLatin: 'Baha porob',
      meaning: 'Flower Festival',
      category: 'trending',
      order: 152,
    ),
    WordModel(
      id: 'w_tr13',
      wordOlChiki: 'ᱛᱩᱢᱫᱟᱜ',
      wordLatin: 'Tumdag',
      meaning: 'Madal / Santali Clay Drum',
      category: 'trending',
      order: 153,
    ),
    WordModel(
      id: 'w_tr14',
      wordOlChiki: 'ᱛᱟᱢᱟᱠ',
      wordLatin: 'Tamak',
      meaning: 'Kettle drum',
      category: 'trending',
      order: 154,
    ),
    WordModel(
      id: 'w_tr15',
      wordOlChiki: 'ᱵᱟᱱᱟᱢ',
      wordLatin: 'Banam',
      meaning: 'Fiddle (Santali instrument)',
      category: 'trending',
      order: 155,
    ),
    WordModel(
      id: 'w_tr16',
      wordOlChiki: 'ᱛᱤᱨᱭᱟᱹᱣ',
      wordLatin: 'Tiryaw',
      meaning: 'Flute',
      category: 'trending',
      order: 156,
    ),
    WordModel(
      id: 'w_tr17',
      wordOlChiki: 'ᱡᱟᱹᱛᱤ',
      wordLatin: 'Jati',
      meaning: 'Tribe / Nation',
      category: 'trending',
      order: 157,
    ),
    WordModel(
      id: 'w_tr18',
      wordOlChiki: 'ᱠᱷᱮᱨᱣᱟᱲ',
      wordLatin: 'Kherwar',
      meaning: 'Ancestral name of Santals',
      category: 'trending',
      order: 158,
    ),
    WordModel(
      id: 'w_tr19',
      wordOlChiki: 'ᱥᱟᱶᱦᱮᱫ',
      wordLatin: 'Sawhed',
      meaning: 'Literature',
      category: 'trending',
      order: 159,
    ),
    WordModel(
      id: 'w_tr20',
      wordOlChiki: 'ᱞᱟᱠᱪᱟᱨ',
      wordLatin: 'Lakcar',
      meaning: 'Culture',
      category: 'trending',
      order: 160,
    ),

    // ── Body Parts (body) ──
    WordModel(
      id: 'w_bd1',
      wordOlChiki: 'ᱵᱚᱦᱚᱜ',
      wordLatin: 'Bohog',
      meaning: 'Head',
      category: 'body',
      order: 161,
    ),
    WordModel(
      id: 'w_bd2',
      wordOlChiki: 'ᱤᱞ',
      wordLatin: 'Il',
      meaning: 'Feather',
      category: 'body',
      order: 162,
    ),
    WordModel(
      id: 'w_bd3',
      wordOlChiki: 'ᱚᱞᱚᱝ',
      wordLatin: 'Olong',
      meaning: 'Forehead',
      category: 'body',
      order: 163,
    ),
    WordModel(
      id: 'w_bd4',
      wordOlChiki: 'ᱢᱮᱫ',
      wordLatin: 'Med',
      meaning: 'Eye',
      category: 'body',
      order: 164,
    ),
    WordModel(
      id: 'w_bd5',
      wordOlChiki: 'ᱞᱩᱛᱩᱨ',
      wordLatin: 'Lutur',
      meaning: 'Ear',
      category: 'body',
      order: 165,
    ),
    WordModel(
      id: 'w_bd6',
      wordOlChiki: 'ᱢᱩ',
      wordLatin: 'Mu',
      meaning: 'Nose',
      category: 'body',
      order: 166,
    ),
    WordModel(
      id: 'w_bd7',
      wordOlChiki: 'ᱞᱩᱴᱤ',
      wordLatin: 'Luti',
      meaning: 'Lip',
      category: 'body',
      order: 167,
    ),
    WordModel(
      id: 'w_bd8',
      wordOlChiki: 'ᱟᱞᱟᱝ',
      wordLatin: 'Alang',
      meaning: 'Tongue',
      category: 'body',
      order: 168,
    ),
    WordModel(
      id: 'w_bd9',
      wordOlChiki: 'ᱰᱟᱴᱟ',
      wordLatin: 'Data',
      meaning: 'Tooth',
      category: 'body',
      order: 169,
    ),
    WordModel(
      id: 'w_bd10',
      wordOlChiki: 'ᱦᱚᱛᱚᱛ',
      wordLatin: 'Hotot',
      meaning: 'Throat',
      category: 'body',
      order: 170,
    ),
    WordModel(
      id: 'w_bd11',
      wordOlChiki: 'ᱛᱤ',
      wordLatin: 'Ti',
      meaning: 'Hand / Arm',
      category: 'body',
      order: 171,
    ),
    WordModel(
      id: 'w_bd12',
      wordOlChiki: 'ᱡᱟᱸᱜᱟ',
      wordLatin: 'Janga',
      meaning: 'Leg / Foot',
      category: 'body',
      order: 172,
    ),
    WordModel(
      id: 'w_bd13',
      wordOlChiki: 'ᱠᱚᱲᱟᱢ',
      wordLatin: 'Koram',
      meaning: 'Chest',
      category: 'body',
      order: 173,
    ),
    WordModel(
      id: 'w_bd14',
      wordOlChiki: 'ᱞᱟᱡ',
      wordLatin: 'Laj',
      meaning: 'Stomach',
      category: 'body',
      order: 174,
    ),
    WordModel(
      id: 'w_bd15',
      wordOlChiki: 'ᱫᱮᱭᱟ',
      wordLatin: 'Deya',
      meaning: 'Back',
      category: 'body',
      order: 175,
    ),
    WordModel(
      id: 'w_bd16',
      wordOlChiki: 'ᱩᱵ',
      wordLatin: 'Ub',
      meaning: 'Hair',
      category: 'body',
      order: 176,
    ),
    WordModel(
      id: 'w_bd17',
      wordOlChiki: 'ᱠᱟᱴᱩᱯ',
      wordLatin: 'Katup',
      meaning: 'Finger',
      category: 'body',
      order: 177,
    ),
    WordModel(
      id: 'w_bd18',
      wordOlChiki: 'ᱨᱟᱢᱟ',
      wordLatin: 'Rama',
      meaning: 'Nail',
      category: 'body',
      order: 178,
    ),
    WordModel(
      id: 'w_bd19',
      wordOlChiki: 'ᱦᱟᱨᱛᱟ',
      wordLatin: 'Harta',
      meaning: 'Skin',
      category: 'body',
      order: 179,
    ),
    WordModel(
      id: 'w_bd20',
      wordOlChiki: 'ᱢᱟᱭᱟᱢ',
      wordLatin: 'Mayam',
      meaning: 'Blood',
      category: 'body',
      order: 180,
    ),

    // ── Food (food) ──
    WordModel(
      id: 'w_fd1',
      wordOlChiki: 'ᱫᱟᱠᱟ',
      wordLatin: 'Daka',
      meaning: 'Cooked Rice / Food',
      category: 'food',
      order: 181,
    ),
    WordModel(
      id: 'w_fd2',
      wordOlChiki: 'ᱫᱟᱜ',
      wordLatin: 'Dag',
      meaning: 'Water',
      category: 'food',
      order: 182,
    ),
    WordModel(
      id: 'w_fd3',
      wordOlChiki: 'ᱡᱮᱞ',
      wordLatin: 'Jel',
      meaning: 'Meat',
      category: 'food',
      order: 183,
    ),
    WordModel(
      id: 'w_fd4',
      wordOlChiki: 'ᱦᱟᱹᱠᱩ',
      wordLatin: 'Haku jel',
      meaning: 'Fish',
      category: 'food',
      order: 184,
    ),
    WordModel(
      id: 'w_fd5',
      wordOlChiki: 'ᱩᱛᱩ',
      wordLatin: 'Utu',
      meaning: 'Curry / Vegetables',
      category: 'food',
      order: 185,
    ),
    WordModel(
      id: 'w_fd6',
      wordOlChiki: 'ᱫᱟᱹᱞ',
      wordLatin: 'Dal',
      meaning: 'Lentil / Pulse',
      category: 'food',
      order: 186,
    ),
    WordModel(
      id: 'w_fd7',
      wordOlChiki: 'ᱵᱩᱞᱩᱝ',
      wordLatin: 'Bulung',
      meaning: 'Salt',
      category: 'food',
      order: 187,
    ),
    WordModel(
      id: 'w_fd8',
      wordOlChiki: 'ᱥᱩᱱᱩᱢ',
      wordLatin: 'Sunum',
      meaning: 'Oil',
      category: 'food',
      order: 188,
    ),
    WordModel(
      id: 'w_fd9',
      wordOlChiki: 'ᱢᱟᱹᱨᱤᱪ',
      wordLatin: 'Maric',
      meaning: 'Chili',
      category: 'food',
      order: 189,
    ),
    WordModel(
      id: 'w_fd10',
      wordOlChiki: 'ᱯᱤᱴᱷᱟᱹ',
      wordLatin: 'Pitha',
      meaning: 'Bread / Cake',
      category: 'food',
      order: 190,
    ),
    WordModel(
      id: 'w_fd11',
      wordOlChiki: 'ᱛᱳᱣᱟ',
      wordLatin: 'Towa',
      meaning: 'Milk',
      category: 'food',
      order: 191,
    ),
    WordModel(
      id: 'w_fd12',
      wordOlChiki: 'ᱫᱟᱦᱤ',
      wordLatin: 'Dahi',
      meaning: 'Curd',
      category: 'food',
      order: 192,
    ),
    WordModel(
      id: 'w_fd13',
      wordOlChiki: 'ᱜᱷᱤᱣ',
      wordLatin: 'Ghiw',
      meaning: 'Ghee / Clarified butter',
      category: 'food',
      order: 193,
    ),
    WordModel(
      id: 'w_fd14',
      wordOlChiki: 'ᱡᱚ',
      wordLatin: 'Jo',
      meaning: 'Fruit',
      category: 'food',
      order: 194,
    ),
    WordModel(
      id: 'w_fd15',
      wordOlChiki: 'ᱩᱞ',
      wordLatin: 'Ul',
      meaning: 'Mango',
      category: 'food',
      order: 195,
    ),
    WordModel(
      id: 'w_fd16',
      wordOlChiki: 'ᱠᱟᱭᱨᱟ',
      wordLatin: 'Kayra',
      meaning: 'Banana',
      category: 'food',
      order: 196,
    ),
    WordModel(
      id: 'w_fd17',
      wordOlChiki: 'ᱠᱟᱱᱛᱷᱟᱲ',
      wordLatin: 'Kanthar',
      meaning: 'Jackfruit',
      category: 'food',
      order: 197,
    ),
    WordModel(
      id: 'w_fd18',
      wordOlChiki: 'ᱜᱩᱲ',
      wordLatin: 'Gur',
      meaning: 'Jaggery',
      category: 'food',
      order: 198,
    ),
    WordModel(
      id: 'w_fd19',
      wordOlChiki: 'ᱪᱤᱱᱤ',
      wordLatin: 'Cini',
      meaning: 'Sugar',
      category: 'food',
      order: 199,
    ),
    WordModel(
      id: 'w_fd20',
      wordOlChiki: 'ᱦᱚᱲᱮᱡ',
      wordLatin: 'Horej',
      meaning: 'Black gram beans',
      category: 'food',
      order: 200,
    ),
  ];

  Future<void> _loadWords() async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      final data = await db.listDocuments(
        'words',
        queries: [Query.orderAsc('order'), Query.limit(500)],
      );
      state = AsyncValue.data(data.map(WordModel.fromJson).toList());
    } catch (e) {
      state = AsyncValue.data(_seedWords);
    }
  }

  Future<void> add(WordModel item) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.createDocument('words', item.id, item.toJson());
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ add word FAILED: $e');
      rethrow;
    }
  }

  Future<void> update(WordModel item) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.updateDocument('words', item.id, item.toJson());
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ update word FAILED: $e');
      rethrow;
    }
  }

  Future<void> delete(String id) async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      await db.deleteDocument('words', id);
      await _loadWords();
    } catch (e) {
      AppLogger.debug('❌ delete word FAILED: $e');
      rethrow;
    }
  }

  Future<void> addWord(WordModel item) => add(item);
  Future<void> updateWord(WordModel item) => update(item);
  Future<void> deleteWord(String id) => delete(id);

  Future<void> seed() async {
    try {
      final db = ref.read(appwriteDbServiceProvider);
      // Fetch all existing documents in the words collection to completely clear legacy records
      final existingDocs = await db.listDocuments('words');
      AppLogger.debug(
        '🧹 Clearing ${existingDocs.length} existing words from database before seeding...',
      );
      for (final doc in existingDocs) {
        final docId = doc['id'] as String;
        try {
          await db.deleteDocument('words', docId);
        } catch (e) {
          AppLogger.debug('⚠️ Failed to delete word document $docId: $e');
        }
      }
    } catch (e) {
      AppLogger.debug('⚠️ Error clearing words collection: $e');
    }

    AppLogger.debug(
      '🌱 Seeding ${_seedWords.length} clean words to database...',
    );
    for (final item in _seedWords) {
      try {
        final db = ref.read(appwriteDbServiceProvider);
        await db.createDocument('words', item.id, item.toJson());
      } catch (e) {
        AppLogger.debug('⚠️ Error seeding word ${item.id}: $e');
      }
    }
    await _loadWords();
  }
}
