import 'package:itun/features/lessons/domain/entities/lesson_entity.dart';
import 'package:itun/features/rhymes/domain/rhyme_model.dart';
import 'package:itun/shared/models/content_models.dart';

extension ContentBlockToLegacy on ContentBlock {
  LessonBlockEntity toLessonBlockEntity() {
    final self = this;
    final blockData = <String, dynamic>{...meta, 'id': id};

    if (self is TextBlock) {
      return LessonBlockEntity(
        type: 'text',
        textLatin: self.textLatin ?? self.markdown,
        textOlChiki: self.textOlChiki,
        audioUrl: self.meta['audioUrl'] as String?,
        data: blockData,
      );
    }
    if (self is ImageBlock) {
      blockData['media'] = self.media.toJson();
      return LessonBlockEntity(
        type: self.media.kind == ContentMediaKind.svg ? 'svg' : 'image',
        textLatin: self.caption,
        imageUrl: self.media.url,
        audioUrl: self.meta['audioUrl'] as String?,
        data: blockData,
      );
    }
    if (self is VideoBlock) {
      blockData['media'] = self.media.toJson();
      if (self.posterUrl != null) blockData['posterUrl'] = self.posterUrl;
      blockData['autoplay'] = self.autoplay;
      if (self.durationSeconds != null) {
        blockData['durationSeconds'] = self.durationSeconds;
      }
      return LessonBlockEntity(
        type: 'video',
        textLatin: self.media.caption,
        imageUrl: self.posterUrl, // legacy: poster in imageUrl
        audioUrl: self.media.url, // legacy: video URL in audioUrl
        data: blockData,
      );
    }
    if (self is AudioBlock) {
      blockData['media'] = self.media.toJson();
      if (self.transcript != null) blockData['transcript'] = self.transcript;
      return LessonBlockEntity(
        type: 'audio',
        textLatin: self.media.caption,
        audioUrl: self.media.url,
        data: blockData,
      );
    }
    if (self is LottieBlock) {
      blockData['media'] = self.media.toJson();
      blockData['loop'] = self.loop;
      return LessonBlockEntity(
        type: 'lottie',
        imageUrl: self.media.url,
        audioUrl: self.meta['audioUrl'] as String?,
        data: blockData,
      );
    }
    if (self is QuizBlock) {
      blockData['quizId'] = self.quizId;
      return LessonBlockEntity(type: 'quiz', data: blockData);
    }
    if (self is GlyphBlock) {
      return LessonBlockEntity(
        type: 'glyph',
        textOlChiki: self.olChiki,
        textLatin: self.latin,
        audioUrl: self.audioUrl ?? self.meta['audioUrl'] as String?,
        data: blockData,
      );
    }
    if (self is CalloutBlock) {
      blockData['style'] = self.variant.name;
      return LessonBlockEntity(
        type: 'callout',
        textLatin: self.text,
        audioUrl: self.meta['audioUrl'] as String?,
        data: blockData,
      );
    }
    if (self is TracingBlock) {
      blockData.addAll(self.config.toJson());
      return LessonBlockEntity(type: 'tracing', data: blockData);
    }
    return LessonBlockEntity(
      type: type,
      audioUrl: self.meta['audioUrl'] as String?,
      data: blockData,
    );
  }
}

extension LessonBlockEntityToContentBlock on LessonBlockEntity {
  /// Converts a legacy [LessonBlockEntity] back to a universal [ContentBlock].
  ContentBlock toContentBlock(int index) {
    // Stable id — generated by editor, preserved here
    final blockId = (data?['id'] as String?) ?? 'blk_${type}_$index';

    // Canonical media lookup
    final dataMedia = (data?['media'] is Map)
        ? (data!['media'] as Map).cast<String, dynamic>()
        : null;

    final canonicalUrl =
        dataMedia?['url'] as String? ?? (type == 'video' ? audioUrl : imageUrl);
    final canonicalFileId = dataMedia?['fileId'] as String? ?? '';

    // Build the meta passthrough — everything in data EXCEPT keys we own
    final meta =
        <String, dynamic>{
          if (audioUrl != null && type != 'audio' && type != 'video')
            'audioUrl': audioUrl,
          ...?data,
        }..removeWhere(
          (k, _) => const {
            'media',
            'posterUrl',
            'quizId',
            'quizRefId',
            'autoplay',
            'durationSeconds',
            'transcript',
            'loop',
            'style',
            'id',
          }.contains(k),
        );

    switch (type) {
      case 'text':
        return TextBlock(
          id: blockId,
          order: index,
          markdown: textLatin ?? textOlChiki ?? '',
          textOlChiki: textOlChiki,
          textLatin: textLatin,
          meta: meta,
        );

      case 'image':
      case 'svg':
        return ImageBlock(
          id: blockId,
          order: index,
          media: ContentMedia(
            url: canonicalUrl ?? '',
            fileId: canonicalFileId,
            kind: type == 'svg' ? ContentMediaKind.svg : ContentMediaKind.image,
          ),
          caption: textLatin,
          meta: meta,
        );

      case 'video':
        return VideoBlock(
          id: blockId,
          order: index,
          media: ContentMedia(
            url: canonicalUrl ?? '',
            fileId: canonicalFileId,
            kind: ContentMediaKind.video,
            caption: textLatin,
          ),
          posterUrl: data?['posterUrl'] as String? ?? imageUrl,
          autoplay: data?['autoplay'] as bool? ?? false,
          durationSeconds: data?['durationSeconds'] as int?,
          meta: meta,
        );

      case 'audio':
        return AudioBlock(
          id: blockId,
          order: index,
          media: ContentMedia(
            url: canonicalUrl ?? audioUrl ?? '',
            fileId: canonicalFileId,
            kind: ContentMediaKind.audio,
            caption: textLatin,
          ),
          transcript: data?['transcript'] as String?,
          meta: meta,
        );

      case 'lottie':
        return LottieBlock(
          id: blockId,
          order: index,
          media: ContentMedia(
            url: canonicalUrl ?? '',
            fileId: canonicalFileId,
            kind: ContentMediaKind.lottie,
          ),
          loop: data?['loop'] as bool? ?? true,
          meta: meta,
        );

      case 'quiz':
        return QuizBlock(
          id: blockId,
          order: index,
          // Accept both old and new key names
          quizId: (data?['quizId'] ?? data?['quizRefId']) as String? ?? '',
          meta: meta,
        );

      case 'glyph':
        return GlyphBlock(
          id: blockId,
          order: index,
          olChiki: textOlChiki ?? '',
          latin: textLatin ?? '',
          audioUrl: canonicalUrl ?? audioUrl,
          meta: meta,
        );

      case 'callout':
        return CalloutBlock(
          id: blockId,
          order: index,
          text: textLatin ?? '',
          variant: CalloutVariant.fromString(
            data?['style'] as String? ?? 'note',
          ),
          meta: meta,
        );

      case 'tracing':
        return TracingBlock(
          id: blockId,
          order: index,
          config: data != null
              ? TracingConfig.fromJson(data!)
              : const TracingConfig(glyph: '', strokes: []),
          meta: meta,
        );

      default:
        return TextBlock(
          id: blockId,
          order: index,
          markdown: textLatin ?? textOlChiki ?? '',
          meta: meta,
        );
    }
  }
}

extension ContentItemToLegacy on ContentItem {
  WordModel toWordModel() {
    final firstAudio = blocks.whereType<AudioBlock>().firstOrNull?.media.url;
    final firstImage = blocks.whereType<ImageBlock>().firstOrNull?.media.url;
    final firstText = blocks.whereType<TextBlock>().firstOrNull?.markdown;

    return WordModel(
      id: id,
      wordOlChiki: olChiki ?? titleOlChiki ?? '',
      wordLatin: title,
      meaning: subtitle ?? '',
      category: categoryId,
      order: order,
      audioUrl: heroMedia?.url ?? firstAudio,
      imageUrl: heroMedia?.url ?? firstImage,
      themeColor: firstText,
    );
  }

  LetterModel toLetterModel() {
    final firstAudio = blocks.whereType<AudioBlock>().firstOrNull?.media.url;
    final firstImage = blocks.whereType<ImageBlock>().firstOrNull?.media.url;
    final firstText = blocks.whereType<TextBlock>().firstOrNull?.markdown;

    return LetterModel(
      id: id,
      charOlChiki: olChiki ?? titleOlChiki ?? '',
      transliterationLatin: title,
      audioUrl: heroMedia?.url ?? firstAudio,
      imageUrl: heroMedia?.url ?? firstImage,
      order: order,
      themeColor: firstText,
    );
  }

  NumberModel toNumberModel() {
    final firstAudio = blocks.whereType<AudioBlock>().firstOrNull?.media.url;
    final firstImage = blocks.whereType<ImageBlock>().firstOrNull?.media.url;
    final firstText = blocks.whereType<TextBlock>().firstOrNull?.markdown;
    final parsedValue =
        int.tryParse(id.replaceAll(RegExp(r'[^0-9]'), '')) ?? order;

    return NumberModel(
      id: id,
      numeral: olChiki ?? '',
      value: parsedValue,
      nameOlChiki: titleOlChiki ?? '',
      nameLatin: title,
      audioUrl: heroMedia?.url ?? firstAudio,
      imageUrl: heroMedia?.url ?? firstImage,
      order: order,
      themeColor: firstText,
    );
  }

  SentenceModel toSentenceModel() {
    final firstAudio = blocks.whereType<AudioBlock>().firstOrNull?.media.url;
    final firstImage = blocks.whereType<ImageBlock>().firstOrNull?.media.url;
    final firstText = blocks.whereType<TextBlock>().firstOrNull?.markdown;

    return SentenceModel(
      id: id,
      sentenceOlChiki: olChiki ?? titleOlChiki ?? '',
      sentenceLatin: title,
      meaning: subtitle ?? '',
      category: categoryId,
      order: order,
      audioUrl: heroMedia?.url ?? firstAudio,
      imageUrl: heroMedia?.url ?? firstImage,
      themeColor: firstText,
    );
  }

  LessonEntity toLessonEntity() {
    return LessonEntity(
      id: id,
      categoryId: categoryId,
      titleOlChiki: titleOlChiki ?? '',
      titleLatin: title,
      order: order,
      estimatedMinutes: durationSeconds != null
          ? (durationSeconds! / 60).round()
          : 5,
      blocks: blocks.map((b) => b.toLessonBlockEntity()).toList(),
    );
  }

  RhymeModel toRhymeModel() {
    final firstAudio = blocks.whereType<AudioBlock>().firstOrNull?.media.url;
    final firstImage = blocks.whereType<ImageBlock>().firstOrNull?.media.url;

    return RhymeModel(
      id: id,
      titleOlChiki: titleOlChiki ?? '',
      titleLatin: title,
      contentOlChiki: olChiki ?? '',
      contentLatin: subtitle ?? '',
      audioUrl:
          audioUrl ??
          (heroMedia?.kind == ContentMediaKind.audio ? heroMedia?.url : null) ??
          firstAudio,
      thumbnailUrl:
          (heroMedia?.kind == ContentMediaKind.image ? heroMedia?.url : null) ??
          firstImage,
      categoryId: categoryId,
      category: category,
      tags: tags,
      coverMediaType: coverMediaType,
      heroMedia: heroMedia,
    );
  }
}
